### ISSUE TITLE
Remove generated files from git

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/MAxO#10]
Files such as this are generated byt the scripts and do not need to be put into the repository.

src/ontology/module/avoid_consumption_of_foods.ofn
src/ontology/module/catalog-v001.xml
src/ontology/module/dosdp-tools.log

remove as git rm ...
add them to .gitignore to keep from accidentally adding them.

**Comment by LCCarmody** [comment]
@pnrobinson  Can we close this ticket?

**Comment by pnrobinson** [comment]
It still seems there are a lot of generated files in the repository, e.g., 
medical_action_ontology.iml
also, we do not need to store the json versions of MAxO like this. We should work out a plan for how we want to release MAxO -- right now the repo might be too complicated for new users?

**Comment by LCCarmody** [comment]
Since there are legacy and we do not plan to use them as moving forward, could we remove them and revisit once there is a plan to move forward? Alternatively, add a 'legacy folder' and move items there?

**Comment by LCCarmody** [comment]
@pnrobinson Also, see #22

**Comment by kingmanzhang** [comment]
I have removed the legacy files and configuration files.
