### ISSUE TITLE
Develop a 'nutritional supplementation' pattern and add new terms

### ISSUE THREAD

**Issue by LCCarmody** [monarch-initiative/MAxO#111]
I'm trying to consolidate several open tickets into one (and add several NTRs).
Reference #4 #41 #42 #88 #66. Will close most of those tickets when everything is captured in new tickets.

  | Term
-- | --
-   [ ] | Betaine supplements,
-   [ ] | folate supplementation
-   [ ] | carnitine supplementation
-   [ ] | methionine supplementation
-   [ ] | creatine supplementation
-   [ ] | arginine supplementation
-   [ ] | biotin supplementation
-   [ ] | folinic acid supplementation
-   [ ] | chenodesoxycholic acid supplementation
-   [ ] | CoQ supplementation
-   [ ] | glycine supplementation
-   [ ] | N-acetylcysteine
-   [ ] | ornithine supplementation
-   [ ] | riboflavin supplementation
-   [ ] | beta-hydroxybutyrate supplementation
-   [ ] | pyridoxine supplementation
-   [ ] | citrulline supplementation
-   [ ] | thiamine supplementation
-   [ ] | amino acid supplementation
-   [ ] | L-serine supplementation
-   [ ] | uridine supplementation
-   [ ] | medium chain supplementation
-   [ ] | essential fatty acid supplementation
-   [ ] | cholesterol supplementation
-   [ ] | zinc supplementation
-   [ ] | Hydroxycobalamin supplementation
-   [ ] | cyanocobalamin supplementation
-   [ ] | methylcobalamin supplementation
-   [ ] | digestive enzyme supplementation

**Comment by ddooley** [comment]
I'll just note that FoodOn will have an interest in referencing or possibly reusing these terms.  We have an additives section we are building out, hopefully through importation of CHEBI terms. Are above terms processes (except for first one?)

**Comment by LCCarmody** [comment]
@ddooley Thanks for this note!    I have an initial list of both CHEBI and whether FOODON has the term (either imported from CHEBI or a separate term).  I initially went with CHEBI because it was more complete, but really, we would want to import from FOODON because these are obviously being used for nutrition supplements.   

To answer your question, we are trying to keep MAXO as entirely as processes.  With our patterns, though, we could import a material and add it to our process term.  The first entry is a mistake.  Given the way we develop patterns, this would be corrected.

Currently, this is the link to our nutrition_supplementation pattern https://github.com/monarch-initiative/MAxO/blob/master/src/patterns/dosdp-patterns/nutrition_supplementation.yaml
We currently use CHEBI in this pattern, but it would be preferable to switch to FOODON (with CHEBI terms imported) instead of having to develop a separate FOODON pattern for additional terms.  
Also, note, there will be additional FOODON tickets. ;) Cheers.

**Comment by LCCarmody** [comment]
Added these currently from Chebi.  Will revisit if/when FOODON adds terms.
