### ISSUE TITLE
Suggested synonym: preventative/preventive

### ISSUE THREAD

**Issue by hannahblau** [monarch-initiative/MAxO#114]
So far as I am aware, "preventative" and "preventive" mean exactly the same thing, so any MAxO term or synonym that contains the word "preventative" could just as easily and correctly be written with the word "preventive". I'm wondering do you want to add these alternative forms as synonyms? The first MAxO term that contains "preventative" is MAXO:0000017. There are 18 occurrences of "preventative" in the latest release of maxo-full.obo.

**Comment by LCCarmody** [comment]
I'll add 'preventive' as a synonym. Although, just a note: there are only 3 labels or terms that this applies to. I am not exactly sure where the 18 number comes from, but could it be that these are synonyms and/or subclasses to these terms? In any event, I will add synonyms to MAXO_0000118, MAXO_0000020, and MAXO_0000017
<img width="942" alt="Screen Shot 2019-10-22 at 9 58 53 AM" src="https://user-images.githubusercontent.com/26067008/67293711-cfd96e00-f4b2-11e9-889d-c300373ce074.png">

**Comment by hannahblau** [comment]
Sorry if I was unclear. The number 18 refers to occurrences of "preventative" both in term names and in synonyms you already defined for those terms. So all the occurrences of "preventative" that are highlighted in yellow in the screen shot above would be included in the total count of 18. I was looking at the "raw" obo file, not the interface you use. But the information should be the same no matter how you see it.
