### ISSUE TITLE
MAxO needs a license

### ISSUE THREAD

**Issue by jmcmurry** [monarch-initiative/MAxO#115]
https://github.com/monarch-initiative/MAxO

**Comment by LCCarmody** [comment]
I was just chatting with @pnrobinson about this.

**Comment by matentzn** [comment]
Any chance we can just make this CC-BY? EBI always gets a bit nervous when I work on open source stuff that uses a non standard licensing system :P generally I think using standard licenses is always good for transparency and portability.

**Comment by LCCarmody** [comment]
@pnrobinson ?  Our discussion was that it should be open for everybody, but we didn't get into the specifics.

**Comment by pnrobinson** [comment]
I think CC-BY is ok, but let's discuss this on the monarch-internal list!

**Comment by cmungall** [comment]
Results of discussion at monarch leadership meeting: We are moving to CC-BY 4.0

**Comment by LCCarmody** [comment]
Okay, will update. Closing.
