### ISSUE TITLE
New object property: restricted_food

### ISSUE THREAD

**Issue by laurenechan** [monarch-initiative/MAxO#119]
Currently I am writing a pattern for the restriction of food (similar to avoidance of food) and we do not have an object property of restricted_food. 

Thoughts on adding one?

**Comment by LCCarmody** [comment]
I think it is a good idea.  I think several of the foods should be on the food restriction and food avoidance list.   Maybe you could help with more substantial definitions distinguishing 'restriction' vs. 'avoidance'?
 I will try to push what I've been doing to the master with the patterns, so you can look at it.  Slight changes...will make a few more, but mostly they are to allow additional synonyms or comments.  I have also added a number of terms to the avoidance tsv file.

**Comment by laurenechan** [comment]
Definitely!
For 'restriction', I see this term as more of a recommendation to limit consumption of something. For example, 'restrict carbohydrate intake' may recommend a limit of X amount of carbohydrates per day, but still allows some to be present in the diet.

For 'avoidance', I find this term to indicate a recommendation to completely keep away from a food item. For example, someone with an allergy may 'avoid seafood intake', with zero intake being the recommendation. 

I look forward to the pattern updates!

**Comment by LCCarmody** [comment]
this was included in 'avoidance' patterns. Closing.
