### ISSUE TITLE
New pattern: sonography by location

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/MAxO#123]
This could be cloned from the MRI one (#26)

NTRs made by the pattern would include

 - https://en.wikipedia.org/wiki/Echocardiography
 - 

But note the existing maxo term assumes 2D. Is this always the case? See https://en.wikipedia.org/wiki/3D_ultrasound

Also: add exact synonym "medical ultrasound" and "diagnostic sonography" to sonography. This is kind of redundant in maxo but may still be useful.

**Comment by LCCarmody** [comment]
Good point about the 2D vs. 3D.  I initially took the info from NCIT (and XREF), but I want it to be a more general term.  2D vs. 3D should be child terms.  A cursory look at Genereviews (first-pass source for terms) shows that they are not specific, although most likely mean 2D.  As we add new prenatal terms, 3D will have greater importance.  

Agree that a new pattern should be made easily.  Will add this to the list for the December release.

**Comment by LCCarmody** [comment]
I'm working on this now.  I changed the definition so it is no longer 2-d specific. 
Questions: Are we absolute on having sonography (and not ultrasonography) as the label?  I have ultrasonography as a label and synonyms for sonography. Largely this is based on NCiT and ERO. 

Also, issue for ultrasonography_by_location patterns, what to do with these terms?:
[Hysterosonography](https://www.ebi.ac.uk/ols/ontologies/ncit/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FNCIT_C38066&viewMode=All&siblings=false)
[Intravascular ultrasound](https://www.ebi.ac.uk/ols/ontologies/ncit/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FNCIT_C99535&viewMode=All&siblings=false)
[Transvaginal ultrasound](https://www.ebi.ac.uk/ols/ontologies/ncit/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FNCIT_C17644&viewMode=All&siblings=false)
[Transrectal ultrasound](https://www.ebi.ac.uk/ols/ontologies/ncit/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FNCIT_C18315&viewMode=All&siblings=false)
[Transabdominal ultrasound](https://www.ebi.ac.uk/ols/ontologies/ncit/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FNCIT_C71375&viewMode=All&siblings=false)

Should these be used in a separate pattern (current pattern is ultrasonography_by_location, i.e., liver ultrasonography and abdominal ultrasonography) some how incorporating 'trans'? or should these be outside of a pattern?  I can't readily find anymore terms, but that doesn't mean there aren't other terms that fall into these categories.

@cmungall @pnrobinson @matentzn @nicolevasilevsky

**Comment by nicolevasilevsky** [comment]
Did you already create this pattern? Can you add the link (I can't find it)

**Comment by LCCarmody** [comment]
Sorry, I merged the branch. It is currently labeled as 'ultrasonography_by_location'

**Comment by nicolevasilevsky** [comment]
it seems like all of the terms you listed above describe an ultrasound inside the tissue/organ, so maybe the solution is to make a new intra-sonography pattern? trans-sonography seems like it could be a synonym.

But maybe the sonography pattern you created would work too. The definition of 'ultrasonography procedure' does not specify whether the procedure is done externally or internally...

**Comment by LCCarmody** [comment]
updated and added all terms with the last merger.  Did not include logical def for the last few terms. Will revisit if needed.
