### ISSUE TITLE
where should associations to diseases/phenotypes live?

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/MAxO#125]
Do we have these yet? Maybe we are not ready but it might make sense to have a simple tsv file we could record some of the more obvious associations, that could be migrated to a full annotation file later.

**Comment by pnrobinson** [comment]
We would like to now create some annotations and discuss the annotation model. We would like to discuss this with the Treatabolome group (SOLVE-RD, Leigh and I are participating)>. This group has lots of good insight as to what needs to be modeled but we all need to implement now. It would be good to have input from the Monarch team!

**Comment by pnrobinson** [comment]
Just made this repo:
https://github.com/monarch-initiative/maxo-annotations
