### ISSUE TITLE
Coordinate therapeutic agent branch with CHIRO

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/MAxO#126]
maxo has an agent branch like this:

![image](https://user-images.githubusercontent.com/50745/69578926-5556af00-0f86-11ea-93c8-40fba7ae4e3a.png)

 - these terms are similar to chebi roles, although the hierarchy is different (e.g. in chebi alkylating agent is under mutagen, and not under anti-neoplastic)
 - @nicolevasilevsky is already doing work to axiomatize the chebi role ontology with https://github.com/obophenotype/chiro - for example, anti-neoplastic agent is defined as having a role that is realized by negatively regulating neoplastic activity

I suggest

 - we make a DP whereby we define X agent using the term X role from chebi
     - e.g. X agent = .. and has_role some ...
     - but note this will not give us the desired inferences, so we should compare the chebi roles with maxo. We can make requests for chebi to change if we like (link back to this ticket)
 - we coordinate on the axiomatization in chiro and in maxo. E.g presumably antineoplastic therapy will have some kind of link to mondo neoplasm. If there are a handful we can do manually. If there are many, then semi-automate

**Comment by LCCarmody** [comment]
I'm not terribly familiar with CHIRO, but certainly would be interested.

**Comment by LCCarmody** [comment]
Moving this to a discussion #213
