### ISSUE TITLE
Excision

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/MAxO#128]
Add term for Excision
link to https://www.ebi.ac.uk/ols/ontologies/ncit/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FNCIT_C15232
for example, surgical removal of cutaneous neurofibroma (https://www.ncbi.nlm.nih.gov/books/NBK1109/)

**Comment by LCCarmody** [comment]
https://forums.studentdoctor.net/threads/the-difference-between-excision-vs-extirpation-vs-enucleation.1241505/
