### ISSUE TITLE
antineoplastics agent therapy

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/MAxO#130]
Should this be antineoplastic agent therapy?
add synonym chemotherapy

**Comment by LCCarmody** [comment]
MAXO_0000062 So you want the label to be antineoplastic agent therapy?  It is currently a synonym. And should chemotherapy be a broad synonym?

We have terms MAXO_0000235 antineoplastic molecular target inhibitor agent therapy or MAXO_0000236 antineoplastic monoclonal antibody agent therapy.

**Comment by pnrobinson** [comment]
It seemed the plural form "antineoplastics" was grammatically incorrect here? I guess chemo does not apply to all of the subterms. Maybe we need some other intermediate level term?

**Comment by LCCarmody** [comment]
I could add a 'chemotherapeutic agent therapy' under antineoplastic agent therapy?
