### ISSUE TITLE
NTR: hot bath/shower

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/MAxO#132]
new term: hot bath/shower
parent: MAXO_0000064 'therapeutic activity intervention' (?)
def: The recommendation to take a hot bath or shower as a therapeutic intervention.

see: https://github.com/monarch-initiative/mondo/issues/1084

**Comment by LCCarmody** [comment]
Maybe this should go under physical therapy? Possible term label of ["Hyperthermic immersion (HI)"](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4049052/) ?  PMID: 28000146 

Additional terms,
- [contrast water therapy](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3633882/)
- [Cold water immersion (CWI) ](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4049052/0)

- [Water immersion](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4049052/)

- [Hydrotherapy](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4049052/)

- aquatic exercise (AE) 

Not sure if should add low-temperature sauna bathing (LTSB), sauna-therapy, sitz bath

**Comment by LCCarmody** [comment]
sorry, warm water immersion therapy for the term label.

**Comment by nicolevasilevsky** [comment]
this sounds good, thanks, Leigh!

Would you like me to do the edits? or will you do them?

**Comment by LCCarmody** [comment]
Actually, I've already done them, but I wouldn't mind if you reviewed them (On Dec. 2019 branch).  Basically, I added a hydrotherapy branch, but I am not confident in location of all the terms. Some terms needed to be in physical therapy and some not.  And should 'irrigation' go under hydrotherapy? OMIT has it that way.  So, if you have a chance (and an opinion), it would be nice if you could look at it.

**Comment by nicolevasilevsky** [comment]
will do!

**Comment by nicolevasilevsky** [comment]
the new terms and classifications look good to me. I did a PR on your branch to edit a tiny typo (and extra space in a text def)
