### ISSUE TITLE
implantable cardioverter-defibrillator

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/MAxO#141]
def: A battery-powered device that is placed under the skin (typically in the left upper chest) with electrode wires that lead into the heart (typically lodging in the apex or septum of the right ventricle). The device can detect abnormal heart rhythms and deliver low-energy or high-energy shocks to interrupt malignant arrhythmia and thereby prevent sudden death.

syn: automated implantable cardioverter defibrillator

Some xrefs:

UMLS_CUI:C0162589
NCIt:C93238

Suggested parent
-- Medical device
----Implantable medical device

NTR Medical device:
def: A piece of mechanical or electronic equipment that is useful for prevention, diagnosis, monitoring, or treatment of disease or other conditions.
xref: NCIt:C16830
(This should be a top level term)

NTR Implantable medical device
-- let's think how this relates to existing MAxO term implantation -- perhaps we do not need this term? @LCCarmody @matentzn

**Comment by LCCarmody** [comment]
My only comment is that MAxO is for medical _actions.  So, the terms could be 'medical device implantation'?  Not sure how to phrase 'implantable cardioverter-defibrillator implantation'.  I think 'medical device implantation' does go under current implantation term.

Also, maybe start a cardiac therapeutic procedure branch, which this could also be under. 
cardiovascualr agent therapy would also go under this branch.

**Comment by pnrobinson** [comment]
I see what you mean...the medical action is actually (1) implantation (2) leaving it there (3) recharging the battery (4) monitoring the device (5) replacing it every 5 years or so etc etc. 
I would suggest that the label of the term should just be "implantable cardioverter defibrillator" because anything else would just be confusing, but the logical definition should be something like 
implantation AND toward some defibrillator AND inheres in some heart ???

**Comment by LCCarmody** [comment]
Maybe 'implantable cardioverter-defibrillator placement'? 

And I'll start an implantation pattern (I have already started one for organ transplant, but I have not implemented it.)

**Comment by LCCarmody** [comment]
implantable cardioverter-defibrillator placement is MAXO_0000474
medical device implantation is MAXO_0000473

This will be available in the next release
