### ISSUE TITLE
NTR: left cardiac sympathetic denervation

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/MAxO#142]
Def: Left cardiac sympathetic denervation (LCSD) is a surgical antiadrenergic intervention with a strong antiarrhythmic effect. LCSD consists in the removal of the left thoracic sympathetic chain and paravertebral ganglia from T1 to T4.  PMID:30972341 

parent -- let's add a new term "surgical denervation" to "surgical procedure" with def: "The resection or complete surgical removal of a nerve"

**Comment by LCCarmody** [comment]
left cardiac sympathetic denervation is MAXO_0000476
surgical denervation is MAXO_0000475
These will be available in the next release

**Comment by pnrobinson** [comment]
thanks so much!
