### ISSUE TITLE
Importing HP

### ISSUE THREAD

**Issue by matentzn** [monarch-initiative/MAxO#146]
Before we can cleanly import HP, we need to fix two things:
- https://github.com/obophenotype/human-phenotype-ontology/issues/4952 (@nicolevasilevsky)
- There is some trouble with one RO relationship. I am on it.

**Comment by matentzn** [comment]
Okay the second thing seems to be fixed in hp-edit, but not in the latest release.. Maybe a syncro issue with the imports.

**Comment by LCCarmody** [comment]
This is done. Still need the fix in #181, but I am closing this ticket.
