### ISSUE TITLE
NTR: Cognitive behavior therapy

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/MAxO#152]
see
https://www.ncbi.nlm.nih.gov/pubmed/29934199

**Comment by LCCarmody** [comment]
May have to rework the 'cognitive and behavioral intervention'  branch.  

We have 
'cognitive and behavioral intervention' MAXO:0000010
-'behavioral counseling'  MAXO:0000077 (Synonym psychotherapy).
Need to work out the structure below this.
