### ISSUE TITLE
Create a medical specialty branch

### ISSUE THREAD

**Issue by LCCarmody** [monarch-initiative/MAxO#155]
Will research and add a list of terms to be added.

**Comment by mellybelly** [comment]
can we get some more background on this need? there are already such nomenclatures out there. seems like the sort of hting that would be referenced within a data model rather than included directly in maxo.

**Comment by matentzn** [comment]
Also in light of the recent EFO presentation, maybe its time to generally try to refer to a canonical set of medical specialities (or what they call therapeutic areas)..

**Comment by LCCarmody** [comment]
This came from another ticket: https://github.com/monarch-initiative/MAxO/issues/154
But the issue was that I wanted to build a few terms using DOSDP patterns using medical specialty under medical examination and medical consultation.

Terms like 'orthopedic consultation', 'dental examination', 'ophtamalogic consultation' and 'eye examination' are all issues.

This started because I wanted to add obstetric terms, like 'fetal examination', so that would have to be in there too (neonatal specialties?)

Looking around, there are a couple of terms in OMIT and a couple in NCIT.  But it is not comprehensive in any way.

Currently, I am trying to gather a comprehensive list of what I think we would need, but it is definitely a bigger undertaking than I had thought. :)

**Comment by LCCarmody** [comment]
Oh, to be clear, I wasn't saying this had to be in MAXO, I was actually looking for this to be elsewhere, but I am not sure where.  If there isn't an obvious place, then it would be a branch that would not be under 'medical actions' because they aren't medical actions.  But having access to an ontology branch with this info would be helpful.

**Comment by mellybelly** [comment]
perhaps having a computable list from https://www.abms.org/ would be ideal. I think this exists somewhere but I can't recollect

**Comment by LCCarmody** [comment]
Yes, they have a list here: https://www.abms.org/member-boards/specialty-subspecialty-certificates/

I don't think MAxO would need all of them, but a complete list  somewhere. should be helpful.

**Comment by pnrobinson** [comment]
These list seems ideal. I theory we could also report what type of specialty usually provides a certain MAxO treatment, but that is likely to be burdensome.

**Comment by LCCarmody** [comment]
Any idea where this should go?

**Comment by LCCarmody** [comment]
@mellybelly Here is a rather quick list of things I am trying to add/deal with for MAxO terms. Mainly consultation and examination. I found so many I didn't look for other use cases, but I know there are others. I  will add those when I find them.

'X' consult
Examples: orthopedic consult, Consultation w/a gastroenterologist, Referral to an orthopedic surgeon, Referral to orthopedist, Consultation w/a pediatric neurologist, Consultation w/a nutritionist, Consultation w/a developmental specialist, Consultation w/a clinical geneticist and/or genetic counselor, Consultation w/a rehabilitation specialist, Referral to neurologist, Referral to craniofacial team, referral to feeding specialist, Consultation w/metabolic physician / biochemical geneticist & specialist metabolic dietician, Referral to developmental pediatrician, Referral to neurosurgeon, Referral to a specialist in pediatric pain management, Referral to a pediatric neurologist, Referral to a palliative care specialist, consultation w/endocrinologist

'X' exam
Examples: eye exam, ophthalmologic assessment/ Ophthalmologic examination, audiology assessment, Dermatologic evaluation, radiologic examination, Neurologic evaluation, Developmental assessment, Neuropsychiatric evaluation, Clinical evaluation of feeding/Feeding and nutrition evaluation, dental evaluation, Endocrine evaluation, Cardiac evaluation

**Comment by pnrobinson** [comment]
Probably for MAxO eye exam and ophthalmology consultation (etc) are close enough to be synonyms ?

**Comment by LCCarmody** [comment]
True, I thought about getting rid of the 'consultation' branch, but they are abundant in GeneReviews.  Exam would also have things like 'fetal exam' and a few other items listed in NCIT: http://www.ontobee.org/ontology/NCIT?iri=http://purl.obolibrary.org/obo/NCIT_C25305

But their group isn't structured, which is why/how this brought me to this question of medical specialties.
