### ISSUE TITLE
Avoidance therapy pattern

### ISSUE THREAD

**Issue by LCCarmody** [monarch-initiative/MAxO#16]
- [ ] Activity avoidance
- [ ] Behavioral avoidance
- [ ] Disease avoidance
- [ ] Environmental avoidance
- [ ] Nutritional avoidance
- [ ] Physiological state avoidance

**Comment by LCCarmody** [comment]
Same issue: https://github.com/monarch-initiative/MAxO/issues/5

**Comment by LCCarmody** [comment]
Start pattern work with ‘Food avoidance’
https://github.com/monarch-initiative/MAxO/issues/48
Medical action avoidance pattern started here: https://github.com/monarch-initiative/MAxO/blob/master/src/patterns/dosdp-patterns/avoidance_of_medical_action.yaml
Tsv file https://github.com/monarch-initiative/MAxO/tree/master/src/patterns/data/manual

**Comment by LCCarmody** [comment]
Not sure if there should be a 'food avoidance' pattern with food terms coming from foodon AND a separate 'nutrition avoidance' pattern with additional terms from another ontology?

**Comment by matentzn** [comment]
They are definetly seperate from the avoidance_of_medical action. I would think one additional pattern is enough: avoidance_of_digestible or some such! this could have as a domain material entity, which would then allow to add stuff like vitamins as well as cheese burgers.

**Comment by LCCarmody** [comment]
Closing this for now. Will open a ticket for each pattern.
