### ISSUE TITLE
ChemicalEntity level measurement pattern? Proteins, pro-proteins and degradation products?

### ISSUE THREAD

**Issue by LCCarmody** [monarch-initiative/MAxO#168]
Would like to make a pattern for ChemicalEntity Level Measurement which would work with UPHENO's [abnormalLevelOfChemicalEntity](https://github.com/obophenotype/upheno/blob/master/src/patterns/dosdp-patterns/abnormalLevelOfChemicalEntity.yaml). (Also, ChemicalEntity activity measurement.)

My issues: 

- The measurements are straight forward for chemical entities presently in CHEBI.  Some proteins are in CHEBI, but many are not. Ticket to add to CHEBI? 

- There are severe 'pro-proteins' that are gene products but not fully processed, such as proinsulin or procalcitonin. Neither in either PR or CHEBI.  Request in CHEBI? PR?

- There are degradation products, ex., D-dimer, that are not in either ontology. 

Current examples:
Term requested | CHEBI ID | PRO ID | MAXO need
-- | -- | -- | --
D-dimer |   |   | Fibrin degradation fragment test
procalcitonin |   |   | procalcitionin level test
proinsulin |   |   | proinsulin measurement, proinsulin to insulin ratio measurement
insulin | CHEBI_145810 | PR_000009054 | insulin level, proinsulin measurement, proinsulin to insulin ratio measurement
creatinine | CHEBI_16737 |   | creatinine level test
Ferritin | CHEBI_82594 | PR_000007693 | ferritin level test, ferritin test
albumin |   | PR_000003918 | albumin level test, albumin to creatinine ration level test
lactic acid dehydrogenase/ lactate dehydrogenase |   |   | lactate dehydrogenase test
creatine kinase | CHEBI_36080 | PR_000029971 | creatine kinase level test
Aspartate aminotransferase |   | PR_000022172 | Aspartate aminotransferase levels
alanine transaminase |   | PR_000008208/PR_000008209 | alanine transaminase test, ALT test
granulocyte colony-stimulating factor |   | PR_000005932 | G-CSF test, G-CSF treatment
Docosahexaenoic Acid | CHEBI_36005 |   | urinary DHA levels
Adenine phosphoribosyltransferase |   | PR_000004175 | Adenine phosphoribosyltransferase (APRT) activity test
Cystatin-C |   | PR_P01034 | cystatin-C level test
protein | CHEBI_36080 | PR_000000001 | protein in urine test
diepoxybutane | CHEBI_23704 |   | DEB/MMC testing
mitomycin C | CHEBI_27504 |   | DEB/MMC testing
iron | CHEBI_18248 |   | iron test/blood iron levels

**Comment by matentzn** [comment]
I would:

0) Ask [obo-discuss](https://groups.google.com/forum/#!forum/obo-discuss) for advice, seems like a good question to pose there
1) Create those MAXO terms you need manually without reference to a chemical ontology where no terms exists
2) Add reference to Chebi were they exist
3) Add reference to PR were no Chebi term exists
