### ISSUE TITLE
NTR: surgical removal of....

### ISSUE THREAD

**Issue by diatomsRcool** [monarch-initiative/MAxO#178]
Need new terms for:
surgical removal of kidney
surgical removal of female gonad
surgical removal of pancreas
surgical removal of liver

Should all be children of surgical excision

**Comment by LCCarmody** [comment]
Will set up this pattern ASAP

**Comment by LCCarmody** [comment]
These are the ones you asked for, but many more were added.  I will be releasing soon with the terms.
MAXO:0001065 | nephrectomy
MAXO:0001067 | oophorectomy
MAXO:0001070 | pancreatectomy
MAXO:0001056 | hepatectomy
