### ISSUE TITLE
NTR: axotomy of....

### ISSUE THREAD

**Issue by diatomsRcool** [monarch-initiative/MAxO#179]
Need new terms...
axotomy of sciatic nerve
axotomy of saphenous nerve

Should be child of surgical procedure OR maybe make a new class "nerve surgery"

**Comment by LCCarmody** [comment]
Potentially, this would be a child of 'surgical denervation'.  However, can you find a use case where this is actually a medical treatment? I find lots of research using axotomies to mimic spinal damage or nerve denervation in animal models, but I don't find any uses where this is a treatment.

**Comment by diatomsRcool** [comment]
Good question. All I have to go on is a list of surgical exposure terms that I got from @nicolevasilevsky . Maybe let's hold off on this one until she gets back.

**Comment by nicolevasilevsky** [comment]
Is there an open action item for me?

**Comment by LCCarmody** [comment]
I'm not sure. But I am not planning to add this unless it is a human therapy of some sort. The only sources I have use this procedure to mimic spinal damage in animal models.  I guess the question is: what's the source?

**Comment by pnrobinson** [comment]
I agree, AFAIK this is an experimental procedure and not something that is used in treatment!

**Comment by diatomsRcool** [comment]
@nicolevasilevsky I guess I need some clarity around why the axotomy terms were in the first version of ECTO. Was it intended to represent an experiment or an actual medical treatment?

**Comment by nicolevasilevsky** [comment]
@diatomsRcool Unfortunately, I don't  know - I didn't add them. Hopefully @cmungall can clarify.

**Comment by mellybelly** [comment]
I think that the axotomy terms belong in OBI for animal experimental procedures and potentially in an ontology consisting of accidental lesions and injuries for human. AFAIK for human, axotomy would only occur in a surgical context where it was not possible to retain connectivity of the axons, but it would not be a therapy in that context. Therefore doesn't go in MAxO i don't think?

**Comment by pnrobinson** [comment]
I have never heard the term axotomy being used in medical contexts, but denervation therapy is roughly the same thing, see e.g. https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5864674/

**Comment by mellybelly** [comment]
hm yes i think this is correct, and there are also other types of denervation that are not axotomy, e.g. ablation of cell bodies. Fantom pain is another example.

**Comment by LCCarmody** [comment]
surgical denervation is in MAXO (MAXO:0000475). If I were to add axotomy, it would be the child of this term. But I think suggesting it go into OBI is a good idea.

**Comment by diatomsRcool** [comment]
So, the next step is an issue in OBI?

**Comment by LCCarmody** [comment]
Possibly. There are a couple of ontologies that have the term, but probably looking to OBI would be good.

**Comment by LCCarmody** [comment]
I am closing this issue. THere are denervation terms, but at least at the moment, I will not add axotomy.
