### ISSUE TITLE
CL import isn't importing logical or asserted class structures

### ISSUE THREAD

**Issue by LCCarmody** [monarch-initiative/MAxO#182]
I don't import CL directly (yet), but through other imports, CL terms get imported into MAXO. However, they are all listed under owl:thing (whether the reasoner is on or off).  There doesn't seem to be any parentage of logical definition associated, so they aren't clustered under CL.  Clearly I can still do my work, but I am wondering why this would be.

Maybe importing CL would fix this?  I do have plans to use this in other patterns, but I haven't gotten to this yet.

**Comment by matentzn** [comment]
I think this makes sense.. Maybe this is a consequence of the HP hack we did; either way I can fix it for you if need be! Just ping me when you know whether you want a CL import or not!

**Comment by LCCarmody** [comment]
Thanks @matentzn Closing ticket
