### ISSUE TITLE
Obsoletion method?

### ISSUE THREAD

**Issue by LCCarmody** [monarch-initiative/MAxO#188]
Based on this discussion, I tested an obsolete, but it didn't work for me.
I got this error. This is not super urgent as there is a functional method of obsoletion available, but I get the error:

"Caused by: java.io.FileNotFoundException: https://raw.githubusercontent.com/monarch-initiative/MAxO/master/components/obsolete.owl"

https://github.com/obophenotype/human-phenotype-ontology/issues/5789#issuecomment-658983438

**Comment by matentzn** [comment]
I dont think this HPO method is compatible with the template-based obsoletion strategy.. Its either or - at least for the foreseeable future!

**Comment by LCCarmody** [comment]
okay. I'm fine with this method. closing
