### ISSUE TITLE
NTR: branched chain amino acid restricted diet intake

### ISSUE THREAD

**Issue by laurenechan** [monarch-initiative/MAxO#191]
Hi, I am interested in this term to use as an example within a project. Are we still interested in adding therapeutic medical diet terms or are we looking at adding them in a different ontology? 

Parent: dietary intervention (MAXO:0000088)
Term: branched chain amino acid restricted diet intake
Definition: Dietary approaches to avoid excess branched chain amino acid (BCAA) intake and elevated plasma BCAA concentrations, including restricted intake of leucine, isoleucine, and valine.
Synonyms: BCAA-restricted diet, low BCAA diet, low branched chain amino acid diet 

Applies to Maple Syrup Urine Disease patients (https://www.ncbi.nlm.nih.gov/books/NBK1319/)

**Comment by LCCarmody** [comment]
Thanks for this. The term 'dietary branched-chain amino acid intake avoidance' MAXO_0010102 (yes, a mouth full!) is in MAXO.  There are a lot of synonyms, but not the ones you suggested. I'm wondering if there should be a new diet term or if this term should include synonyms?

**Comment by laurenechan** [comment]
@LCCarmody Thanks for bringing that term up, I think that will work fine for my purposes. I do think we should consider adding the 'low BCAA diet' and 'low branched chain amino acid diet' synonym terms as these are terms I've known clinicians to use. 
These two terms pretty much describe the same thing, the only difference to me feels like we either focus on the avoided item or we focus on the food still being consumed while avoiding the item. Either way, I don't think they are distinct enough to require separate terms. 
Let me know if you'd like me to add the synonyms in!

**Comment by LCCarmody** [comment]
Happy to add the synonym, although, I think it should be 'low BCAA diet intake' or 'low BCAA diet recommendation' and make sure it is an action.  This term was built using a pattern--which means I wouldn't edit it with Protege and just add it to the TSV file. If you are interested, I can show you how to do it/where to look.  

If not, it is no problem for me to add it.

**Comment by laurenechan** [comment]
I think I found the tsv, I've made a PR for those changes so I'll close this issue. Thanks!
