### ISSUE TITLE
duplicate definitions

### ISSUE THREAD

**Issue by diatomsRcool** [monarch-initiative/MAxO#218]
Looks like nonsteroidal anti-inflammatory agent therapy has the same definition as anti-inflammatory agent therapy. It's causing some errors in ECTO.

**Comment by LCCarmody** [comment]
Thanks. I will get to this soon.

**Comment by LCCarmody** [comment]
Actually, I think the issue is that they had the same synonyms (and not the same definition).  This will be fixed in the next release.
