### ISSUE TITLE
Review relationships used in Maxo

### ISSUE THREAD

**Issue by matentzn** [monarch-initiative/MAxO#220]
During our next call, we should look at the relationships you are using; some of them https://www.ebi.ac.uk/ols/ontologies/maxo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMAXO_0000221

You cant inhere in a role!

**Comment by LCCarmody** [comment]
yes, this is one of the issues I was going to talk about...after a discussion with @cmungall during a discussion about CHIRO. WE have several things to discuss--this among it. :)

**Comment by LCCarmody** [comment]
Completed.
