### ISSUE TITLE
Be careful not to use chemical entities in chemical role patterns!

### ISSUE THREAD

**Issue by matentzn** [monarch-initiative/MAxO#224]
![image](https://user-images.githubusercontent.com/7070631/111447529-70ae7600-8705-11eb-91d3-87b6a9e37d29.png)

We will discuss this at our meeting later :)

**Comment by matentzn** [comment]
We need to include BFO to avoid this in the future.

**Comment by LCCarmody** [comment]
Yes, I think @cmungall said this might be an issue. I thought I had limited to just the role branch, but clearly I did not.

**Comment by ddooley** [comment]
Just saying - I've asked CHEBI to add word "role" to all of their role branch terms to facilitate people understanding what is a role and what isn't, but they shied away from that.  But many of their "roles" are literally defined as material entities in text, a double confuser!  In the end as a temporary workaround I had to simply take their whole "role" branch and move it up to owl:Thing to stop logical contradictions at moment in working with CDNO which uses vitamins under a material entity branch of chemicals.

**Comment by matentzn** [comment]
Hahha nice @ddooley

**Comment by LilyAndres** [comment]
Hi just following this issue, I think CHEBI is planning to move roles into CHIRO? Is this going to happen soon? Or I'm missing something that I don't know?

**Comment by LCCarmody** [comment]
@LilyAndres

**Comment by nicolevasilevsky** [comment]
as far as I understand, CHIRO will represent chemical roles

**Comment by cmungall** [comment]
OK, a lot to unpack here.

But yes, @matentzn is correct that we absolutely need to avoid this. It isn't necessary to import BFO to get error checking though. It should be sufficient to import RO (I haven't checked this though).

@ddooley I agree 100%, CHEBI have made this super-confusing, it's like a partial attempt to map things into a BFO universe that was not fully done and everyone is just confused. I agree they should just append 'role' onto the label to at least help signify that this is not a structure. Although your current solution of moving role up to Thing is potentially making things worth further down the line.

I also think they should just represent some of their roles as structures.

CHIRO doesn't help you here. CHIRO axiomatizes CHEBI roles. So if you have a CHEBI role "foo inhibitor", CHIRO will tell you this is a subclass of inhibits some foo. This will allow you to "compile away" some roles (i.e. you can just have a direct inhibits link to foo). And it especially doesn't help you in this case where you are using a structure (corticosteroid) as a role.

**Comment by matentzn** [comment]
> But yes, @matentzn is correct that we absolutely need to avoid this. It isn't necessary to import BFO to get error checking though. It should be sufficient to import RO (I haven't checked this though).

I think you need the disjointness axiom (continuant dsj. occurrent) or some such to get the reasoner to howl. Maxo already imports RO!

**Comment by ddooley** [comment]
I don't mean for role as immediate subclass of Thing to be permanent.  Its just that FoodOn has to wait until external ontologies solve this (in my view CHEBI's problem) before it can be moved back to its proper place there.

**Comment by mellybelly** [comment]
There are many roles that are not well served at this time, perhaps we need an RO for roles of sorts? or is this what CHIRO is intended to be longer term? I am a bit confused ;-).

**Comment by LCCarmody** [comment]
I have made 2 patterns--one with material entity and one with role and split the terms into their respective patterns. (This was actually done quite a while ago, but I am just realizing this was pertinent to this discussion.

Closing the ticket for now, but open to further discussion about CHEBI roles at a later time.
