### ISSUE TITLE
Tracheobronchoscopy

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/MAxO#249]
Inspection of the interior of the bronchi and trachea, i.e., of their lumen and mucous membranes. Tracheobronchoscopy is performed by a rigid or flexible endoscope which is inserted into the lumen of the trachea, and then into the bronchi. Both endoscopes are used.

Note that endoscopic procedure is now listed as "therapeutic", but endoscopy can be used for diagnosis or therapy or both. I would suggest we rename the current term

https://www.ebi.ac.uk/ols/ontologies/maxo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMAXO_0000130

To "Therapeutic endoscopic procedure"

and add a new parent term

Diagnostic endoscopic procedure

underneath https://www.ebi.ac.uk/ols/ontologies/maxo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMAXO_0000003&viewMode=All&siblings=false

Diagnostic endoscopic procedure
synonym Diagnostic endoscopy
Def:Investigation of a hollow organ with an endoscope, a rigid or flexible tube with a light and a camera. In some cases, therapeutic actions may be performed in combination with diagnostic endoscopy.

**Comment by pnrobinson** [comment]
after this term is created in MaXo, let's create an issue on the HPO tracker to add this diagnostic modality to the HPO term Bronchial hemorrhage.

**Comment by LCCarmody** [comment]
added term
