### ISSUE TITLE
Preimplantation genetic testing - new term

### ISSUE THREAD

**Issue by peupeubangbang** [monarch-initiative/MAxO#251]
**Preferred term label:**
Preimplantation genetic testing

**Synonyms**
Preimplantation genetic diagnosis
Preimplantation genetic screening
PGT
PGD
PGS

**Definition (free text, please give PubMed ID, if applicable, in format PMID:#######)**
GeneReviews:NBK5191
Genetic testing of one or more cells removed from early embryos conceived by in vitro fertilization and transferring to the mother's uterus only those embryos determined not to have the pathogenic variant(s)/chromosome anomaly(ies) of concern.

**Parent term**
MAXO:0000529
Prenatal genetic testing
MAXO:0000533
Molecular genetic testing

**Children terms (if applicable)**
Suggest making below term obsolete due to redundancy since **molecular** level prenatal genetic testing is (within the limits of current technology) limited to testing of embryos i.e. preimplantation genetic testing, and does not include the rest of the methods described in the definition.
MAXO:0000532
Prenatal molecular genetic testing

**Comment by LCCarmody** [comment]
Hi, thanks for the suggestions. Will look to add these in the next month or so.
