### ISSUE TITLE
MRE term needs for ECTO

### ISSUE THREAD

**Issue by laurenechan** [monarch-initiative/MAxO#256]
Hello,
I was just reviewing the gap analysis of MRE terms that we were hoping to include in ECTO (https://github.com/EnvironmentOntology/environmental-exposure-ontology/issues/6). I had a few questions regarding MRE/new ECTO terms that I believe should reference MAxO terms. Could we please discuss what MAxO terms might be useful for these ECTO terms to reference, or can we consider developing some new MAxO terms? 

MRE:0000003 Diagnostic medical exposure - is exposure to a medical action appropriate enough? 

MRE:0000006 Interventional radiological procedure - is this distinct from exposure to a radiograph? Does it need to have an interventional aspect?

Also, I am uncertain we have a MAxO term for any of the following items, would we be open to creating these classes?
MRE:0000027 Nuclear medicine procedure
MRE:0000029 Pelvis radiograph
MRE:0000030 Skull radiograph
MRE:0000031 Intravenous pyelogram

**Comment by LCCarmody** [comment]
Hi, sorry about the delay...It will still be some time before this can be implemented.

There is a 'head radiograph procedure', 'abdominal radiograph procedure', and 'diagnostic procedure', and 'radiograph imaging procedure'.  I'm not sure if that is close enough for your purposes?  The other terms would need to be added.

**Comment by laurenechan** [comment]
SO glad to have you back, @LCCarmody! Truthfully, I am not entirely sure how distinct the intended terms here need to be as they were developed in a list prior to me joining the lab. I believe these came from @pnrobinson , who can likely help us decipher how specific our MAxO terms would need to be if we are creating exposure terms to reference them.

**Comment by LCCarmody** [comment]
MAXO_0009052 nuclear medicine procedure
MAXO_0001253 pelvic radiograph procedure
MAXO_0001254 skull radiograph procedure
MAXO_0009065 intravenous pyelogram
are added and will be available in the next release.
