### ISSUE TITLE
Assessment of intellectual abilities

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/MAxO#262]
new term:
Assessment of intellectual abilities

parent:
MAXO_0000003 'diagnostic procedure'

@LCCarmody is this in scope? If yes, I can add it

needed for Arts Syndrome   OMIM:301835 MONDO:0010533

**Comment by LCCarmody** [comment]
Generally, I have been curating to MAXO:0000709 developmental-behavior pediatrician evaluation. We may need a term for developmental-behavior assessment. I am not sure I would put assessment of intellectual abilities unless there is a specific test that is conducted.

**Comment by nicolevasilevsky** [comment]
@pnrobinson will ask Ben Coleman about this to find out what the specific test should be called

**Comment by LCCarmody** [comment]
Asked @bcoleman96 via slack

**Comment by nicolevasilevsky** [comment]
I think that's okay.

Note to self - add this treatment for:
intellectual disability in Saethre-chotzen Syndrome too

**Comment by LCCarmody** [comment]
added a branch. will be available in the next release. Thanks
