### ISSUE TITLE
NTR: cochlear implant

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/MAxO#264]
new term: cochlear implant
parent: 'medical device implantation'

needed for Arts Syndrome   OMIM:301835 MONDO:0010533
tx for hearing impairment/Sensorineural hearing loss

(@LCCarmody if this looks okay to you, i can add it)

**Comment by LCCarmody** [comment]
Is cochlear implant an action or the device? I see that OLS has imported snomed terms. Maybe the structure should be 'implantation of cochlear hearing device'?  Or other possible label?
