### ISSUE TITLE
NTR cataract surgery 

### ISSUE THREAD

**Issue by sabrinatoro** [monarch-initiative/MAxO#265]
Alternative name: Surgical treatment of ocular cataract

definition: 
Surgical removal procedure of cataract

parent: 
- surgical removal procedure (MAXO_0000885)
- we could probably be more precise, eg. surgical extirpation, though depending on the severity of the cataract, it wouldn't be 'solid matter'. 

Note: I can add this term myself, but I need someone to confirm what the parentage should be.

**Comment by LCCarmody** [comment]
I think it should be under surgical excision, BUT I think this would not be added via protege and would use a pattern (removal of phenotype) using HPO term to build it.

Also, interestingly enough, snomed describes extirpation as a modifier of excision. So, may have to think about that.
