### ISSUE TITLE
enucleation

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/MAxO#266]
The definition is slightly wrong. In the vast majority of usages, this refers to the eye, e.g., 
https://pubmed.ncbi.nlm.nih.gov/10667436/

There is also tumor enucleation 

You would not say enucleation of a liver etc.,

I think it might be better to have
enucleation of the eye
synonym: enucleation
Enucleation describes the removal of the entire globe, with separation of all connections from the orbit, including optic nerve transection. 
PMID: 32965815

(https://eyewiki.aao.org/Enucleation)

I had never heard the term tumor enucleation and I do not think it is very useful, because we would need the cross product of all of the ectomy terms in Maxo.

**Comment by LCCarmody** [comment]
I am fine with changing it based on a source, but that definition was taken directly from NCIT (xrefed).

**Comment by LCCarmody** [comment]
There are other papers that refer to 'enucleation of tumors' (https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5633775/)
and such. I wonder if enucleation of the eye should be a child term and this term be more broad?
