### ISSUE TITLE
NTR: Stereotactic radiosurgery

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/MAxO#275]
NTR: Stereotactic radiosurgery
syn: gamma knife surgery

Needed for annotation of Neurofibromatosis, Type Ii   OMIM:101000 MONDO:0007039
From https://www.ncbi.nlm.nih.gov/books/NBK1201/:
"Stereotactic radiosurgery, most commonly with the gamma knife, has been offered as an alternative to surgery in select individuals with vestibular schwannoma."

**Comment by LCCarmody** [comment]
Added 'sterotactic radiation therapy'
'stereotactic radiosurgery'
'sterotactic radiosurgery using proton beam therapy'
'sterotactic radiosurgery using Gamma Knife'
'sterotactic radiosurgery using Linear Accelerator'
'sterotactic body radiation therapy'
