### ISSUE TITLE
GABA transaminase inhibitor agent therapy

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/MAxO#278]
Administration of a GABA transaminase inhibitor agent. Agents such as vigabatrin are used in the treatment of refractory seizures and infantile spasms.

Also annotation
https://pubmed.ncbi.nlm.nih.gov/32369862/
OMIM:617698 , 3-methylglutaconic aciduria, type IX

**Comment by LCCarmody** [comment]
CHEBI:63674 - EC 2.6.1.19 (4-aminobutyrate—2-oxoglutarate transaminase) inhibitor.

**Comment by LCCarmody** [comment]
term added
