### ISSUE TITLE
Proposal: do not capitalize class labels

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/MAxO#29]
Rationale:

 * lowercase for non-proper is OBO standard
 * lowercase is better for auto-composition of labels
 * If applications prefer uppercasing initial letter, this is trivial to do at application time or during release pipeline
 * The converse is not true, as there is no way to deterministcally know if a leading uppercase letter is for a proper or non proper name

**Comment by LCCarmody** [comment]
@nicolevasilevsky All of the labels need to be changed to lower case.  I did not opt to have this scripted because it is a handy way to tell whether I have checked/edited a term.

**Comment by nicolevasilevsky** [comment]
@LCCarmody yes, I think for things like MRI, it would be capitalized.

**Comment by nicolevasilevsky** [comment]
I think I'm all done. @LCCarmody do you want to double check and close if everything looks okay?

**Comment by LCCarmody** [comment]
Looks good. WIll close.
