### ISSUE TITLE
NTR: needed for 129500 CLOUSTON SYNDROME

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/MAxO#298]
to treat Nail dystrophy HP:0008404
- [x] Filing or drilling of hyperkeratotic nails
- [ ] Artificial nails

to treat Palmoplantar hyperkeratosis
- [x] Bland skin emollients may help soften hyperkeratosis.
- [x] Keratolytic preparations (containing e.g. urea, salicylic acid, lactic acid) may be helpful.
- [x] Regular filing or paring of hard skin can ↓ pain & improve function

see https://www.ncbi.nlm.nih.gov/books/NBK1200/

**Comment by LCCarmody** [comment]
For Nail dystrophy, I think the term is nail debridement. I am not sure if we should include method of debridement (i.e., drilling or grinding or filing). Maybe just add a comment?

For palmoplantar hyperkeratosis, 
-application/use of emollient
- keratolyic agent therapy (possibly add salicylic acid, etc. as children, but not sure it is necessary now?)

As for the removal of hard skin, I'm not sure that these suffice. 
- debridement of skin
- desloughing of skin/removal of slough from skin
- surgical removal of skin

**Comment by LCCarmody** [comment]
- paring or cutting of benign hyperkeratotic lesion
- removal of callus

Obviously, we will need a skin procedure category to group these.

**Comment by LCCarmody** [comment]
adding all terms except artificial nail. I don't believe that is in scope.
