### ISSUE TITLE
Proposal: reuse upper level OBI classes

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/MAxO#30]
OBI has classes for Assay (test), biopsy, etc. These could be used in dosdp files and used as upper level classes in MAXO

**Comment by bpeters42** [comment]
This ticket makes it pretty clear that MAxO has no intention of conforming with OBO foundry principles; why are you applying for a purl then?

**Comment by ddooley** [comment]
On our call today we discussed "biopsy" that Chris raised in (https://github.com/obi-ontology/obi/issues/1072), and see that it would be a specimen collection process.  It currently is listed under ERO, so I am following up with ERO to see about importing it and its subclasses into OBI.

I'll just add that it is incumbent on us at OBI to understand any class structure issues that make MAXO curators shy of integrating ... we would appreciate knowing what barriers to adoption you see in particular.

**Comment by LCCarmody** [comment]
Hey @ddooley we are happy to align on biopsy.  Please see: https://github.com/obi-ontology/obi/issues/1072#issuecomment-556023258

**Comment by LCCarmody** [comment]
Add Collecting with a swab: use for swab collection pattern http://purl.obolibrary.org/obo/OBI_0002600
