### ISSUE TITLE
New terms for Alagille Syndrome

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/MAxO#300]
See https://www.ncbi.nlm.nih.gov/books/NBK1273/
OMIM:118450

New terms needed:

For Gastrointestinal symptoms:
1. Clotting studies for GI symptoms
2. Serum bile acids
3. Fat-soluble vitamin levels
4. Technitium-99m-DISIDA scintiscan
5. Hepatic ultrasound

For failure to thrive:
1. gastrostomy tube
2. Nasogastric feeds

**Comment by LCCarmody** [comment]
What are the clotting studies?

Is the term measurement of serum biles?

Just added fat soluble vitamin level measurement (will be available in next release), but is there an additional term?

Any info on number 4?

Liver ultrasound already exists--will add synonym.

**Comment by nicolevasilevsky** [comment]
We can close this - these terms are no longer needed as we aren't adding annotations for evaluates/investigates.
