### ISSUE TITLE
evaluation terms should not be children of a procedure

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/MAxO#305]
per [POET call](https://docs.google.com/document/d/1cJuO1Dm1I09YmJsgZs4JcPi8pnqhClm2rPDe1KViu_I/edit#) on 2022-05-31

evaluation terms should not be children of a procedure,e g 'orthopedic surgeon evaluation' should not be a subclassOf 'orthopedic procedure'

@LCCarmody please feel free to reassign to me, if you like

**Comment by LCCarmody** [comment]
I fixed this previously, unfortunately, I did not close this ticket. THis is done. apologies.
