### ISSUE TITLE
NTR: immunosuppressant avoidance

### ISSUE THREAD

**Issue by sabrinatoro** [monarch-initiative/MAxO#307]
Need term for "immunosuppressant avoidance"
Parent term: 'therapeutic avoidance intervention' (MAXO:0000151)

Should conform to : https://github.com/monarch-initiative/MAxO/blob/master/src/patterns/dosdp-patterns/avoidance_of_medical_action.yaml
in which "medical action" should be: immune suppressant agent therapy (MAXO:0000297)

**Comment by LCCarmody** [comment]
Added term! Thanks
