### ISSUE TITLE
NTR: supplementation terms

### ISSUE THREAD

**Issue by sabrinatoro** [monarch-initiative/MAxO#308]
**NTR: vitamin K supplementation** 
Should follow the pattern: https://github.com/monarch-initiative/MAxO/blob/master/src/patterns/dosdp-patterns/nutrition_supplementation.yaml
Where chemical_entity = CHEBI:28384

**NTR: fat-soluble vitamin supplementation**
This term could be the parent term for 
vitamin D supplementation
vitamin K supplementation
vitamin E supplementation
vitamin A supplementation
See: https://www.ebi.ac.uk/chebi/chebiOntology.do?chebiId=24020
However, this term wouldn't follow the existing pattern since CHEBI:24020 referring to "fat-soluble vitamin" is not in the "CHEBI:24431" branch (for what I can tell).

**NTR: cholic acid supplementation** 
Should follow the pattern: https://github.com/monarch-initiative/MAxO/blob/master/src/patterns/dosdp-patterns/nutrition_supplementation.yaml
Where chemical_entity = CHEBI:16359

**Comment by LCCarmody** [comment]
added fat-souble vitamin supplementation terms and re worked the patterns that they have the vitamin terms vitamin D supplementation
vitamin K supplementation
vitamin E supplementation
vitamin A supplementation

are children of this term. 

Vitamin E term was added. Also added micronutrient supplementation and macronutrient supplementation (as CHEBI defines some material entities as having micronutrient and macronutrient roles).  Closing this ticket.
