### ISSUE TITLE
NTR: adrenal replacement therapy + general hormone replacement therapy terms

### ISSUE THREAD

**Issue by sabrinatoro** [monarch-initiative/MAxO#309]
NTR: adrenal replacement therapy
Definition: Hormone replacement therapy that involves replacing the hormones that the adrenal glands no longer produce, including cortisol. 

Do we need a parent term "hormone replacement therapy" or "Replacement Therapy"? 
definition: Administration of a body substance to compensate for the loss, as from disease or surgery, of a gland or tissue that would normally produce the substance. 
(http://purl.obolibrary.org/obo/NCIT_C15471)

Currently, there is a term: "hormone modifying therapy" (MAXO:0000283)
Definition: Use of any agent that can alter hormone levels or modulate hormone effects.
This term is related to, but not quite a synonym of the concept of "hormone replacement therapy". 
Similarly, "adrenal-modifying, hormonal agent therapy" 
Definition: Use of any agent that can alter adrenal gland functions.
This term is related to, but not synonym as "adrenal replacement therapy"

**Comment by sabrinatoro** [comment]
Another NTR required: Sex hormone replacement therapy

**Comment by LCCarmody** [comment]
I am adding adrenal replacement therapy. I specifically don't want to add hormone replacement therapy as a term, because that is nearly always referring to estrogen or postmenopausal therapies--but not always. It is too confusing to have that as a parent term. I will add specific HRT, like adrenal

**Comment by LCCarmody** [comment]
closing. Will work further on hormone replacement on another ticket
