### ISSUE TITLE
Canaloplasty

### ISSUE THREAD

**Issue by Sukramg** [monarch-initiative/MAxO#311]
**Definition** 
non-penetrating surgery for the reduction of intraocular pressure in patients affected by glaucoma
https://eyewiki.aao.org/Canaloplasty

PMID: 30488337

In analogy to the German OPS system
5-134.2  Viscocanaloplasty

https://www.icd-code.de/ops/code/5-134.html

The Operation and Procedure Code (OPS) is the official classification for coding operations, procedures and general medical measures in Germany and is published annually by the German Institute for Medical Documentation and Information (DIMDI) on behalf of the Federal Ministry of Health.

**Synonyms**
Viscocanaloplasty

**Parent term**
Deep sclerectomy

**Comment by LCCarmody** [comment]
Hi. I am so sorry for the delay in getting back to this ticket. I am adding these terms now, but MAxO is definitely in need help in the ophthalmology area.

We do not have (but will include) sclerectomy, deep sclerectomy and canaloplasty. Please let us know if there are additional terms needed.

**Comment by Sukramg** [comment]
Thank you very much! Yes, I will add more terms, the ones you mentioned and others too.
