### ISSUE TITLE
NTR: 3D facial analysis

### ISSUE THREAD

**Issue by peupeubangbang** [monarch-initiative/MAxO#313]
**NTR**: 3D facial analysis
**Synonyms**: three dimensional facial analysis, 3D facial assessment, three dimensional facial assessment, 3D facial measurement, three dimensional facial measurement
**Definition**: Computer aided analysis of 3D facial images to detect abnormal facial phenotypes that assist in diagnosis, treatment monitoring and surgical planning
**Parent term**: Clinical imaging procedure (MAXO:0000005) OR I could add another NTR for medical photography (2D/3D) underneath this?
**PMID**: 34108542

Happy for suggestions :)

**Comment by LCCarmody** [comment]
I am sorry for the long delay on this term. I am wondering if there could be more to this branch? I assume you have a specific use case, but I am wondering if a more general head measurement/facial measurement terms could be added.

EFO has 'facial morphology measurement' and SNOMED has facial measurement for eyeware fitting. I am wondering what 

So thinking something that could encompass all of this.

'body measurment'
    'head measurement'
         face measurement
              face measurement by type?
                    3D facial analysis.
              facial morphology measurement
                     3D facial analysis
                     
Feel. free to add suggestions.

**Comment by peupeubangbang** [comment]
@LCCarmody thanks for your good suggestions. 

i just saw there was a NTR for dysmorphology assessment which is very much the goal here but limited to the face. 

wondering if i should potentially go in that branch with dysmorphology assessment as parent term?

**Comment by LCCarmody** [comment]
Would facial dysmorphology assessment be a helpful term for you? I am not sure but facial morphology measurement could be synonym to facial dysmorphology assessment. But I need to think about it. 

The terms I just added are added quickly because we are going to add MAXO annotations to HP terms on the hpo website. Hope it will go live next week. So, I will definitely need to rework the branch. I can add this term quickly as well, but you can expect some adjustments with respect to the branch.

**Comment by LCCarmody** [comment]
Added a number of terms. This term also has Clinical imaging procedure (MAXO:0000005) as a parent.  These branches will still require a lot to fill out completely.
<img width="436" alt="Screen Shot 2023-04-13 at 1 01 09 PM" src="https://user-images.githubusercontent.com/26067008/231832331-0d3fb3b4-4e13-425d-a7c9-9f87064dda3e.png">

Do you want to add your orcid id as a contributor?

**Comment by peupeubangbang** [comment]
Thanks @LCCarmody this is great! no need for ocrid just happy to contribute. If branch changes and this term no longer suits then facial (dys)morphology assessment also a good option for us. 

I am wondering if perhaps there are some maxolyzer annotations that could be done with 3D imaging but I will chat to some people
