### ISSUE TITLE
NTR: diathermy

### ISSUE THREAD

**Issue by sabrinatoro** [monarch-initiative/MAxO#323]
NTR: diathermy
Definition: Diathermy is a therapeutic treatment that uses a high-frequency electric current to stimulate heat generation within body tissues.

3 types (maybe children?)
- Radio wave Diathermy (aka: high-frequency diathermy and shortwave diathermy; diathermy that uses high-frequency electromagnetic currents)
- Microwave Diathermy (diathermy that uses microwave)
- Ultrasound diathermy (aka ultrasonic therapy; diathermy that uses high-frequency sound )

parent: 
could probably be "radiation therapy", though I don't think the current definition for "radiation therapy" really work for "diathermy"
OR maybe the parent should be "thermal ablation therapy"

information from 
https://www.webmd.com/pain-management/what-is-diathermy
https://www.healthline.com/health/diathermy
https://www.fda.gov/inspections-compliance-enforcement-and-criminal-investigations/inspection-guides/diathermy

**Comment by LCCarmody** [comment]
Finally adding this. Right now it is going to just be a therapeutic procedure. Some of these are also specific area types of therapy (i.e., physical therapy), so as I build out those branches, will add.

Sorry for the long delay.

**Comment by sabrinatoro** [comment]
I don't think that this issue is closed. 
The term needed is "diathermy". Most diathermy treatments relieve pain, tension, and inflammation in the muscles and joints.

The term added (ultrasonography) is for imagining.

**Comment by sabrinatoro** [comment]
I didn't see them in Poet and ols. It must be taking some time to get there. 
Thank you!

**Comment by LCCarmody** [comment]
FYI, new OLS is working again. https://www.ebi.ac.uk/ols4/ontologies/maxo/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FMAXO_0000026

**Comment by LCCarmody** [comment]
can I close this?
