### ISSUE TITLE
NTR: intravitreal treatment 

### ISSUE THREAD

**Issue by sabrinatoro** [monarch-initiative/MAxO#324]
definition: 
pharmacotherapy delivered by injection in the intravitreal region 

vitreous chamber of eyeball: http://purl.obolibrary.org/obo/UBERON_0001799

**Comment by LCCarmody** [comment]
Sorry for the lengthy delay. I think what is lacking is the method of delivery under pharmacotherapy.
oral, parenteral (injected), sublingual, topical, transdermal, nasal, ocular, rectal, vaginal are some of the methods.
This would be parenteral and ocular? Need to think about how/if to make a pattern.

**Comment by LCCarmody** [comment]
This has been delayed due to discussion about 'route of administration'

**Comment by LCCarmody** [comment]
i added this to a branch of 'route of administration', but not specifically the pharmacotherapy branch. thanks.
