### ISSUE TITLE
NTR: FM amplification system

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/MAxO#326]
@LCCarmody would FM amplification system for hearing loss be an appropriate MAxO term (see https://www.healthyhearing.com/help/assistive-listening-devices/fm-systems) or should we just annotate to Hearing Aid Usage?

It is in NCIT: NCIT:C183183 FM Hearing Aid System

@lopierra

**Comment by LCCarmody** [comment]
I guess it depends what the use case is. Maybe child term like 'hearing aid with FM amplifcation system usage' or 'use of hearing aid with FM amplification'?

**Comment by nicolevasilevsky** [comment]
either of those sound good to me, thank you!

**Comment by LCCarmody** [comment]
added.
