### ISSUE TITLE
NTR: Fundoplication

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/MAxO#327]
NTR: fundoplication

parent: MAXO:0000004 surgical procedure

def: A therapeutic surgical procedure to treat gastroesophageal reflux disease and hiatus hernia. It involves the wrapping of the fundus of the stomach around the lower esophagus to strengthen the lower esophageal sphincter.
source: NCIT:C91834

xref: NCIT:C91834

needed for INCLUDE @lopierra

**Comment by twhetzel** [comment]
Any updates on adding this term?

**Comment by twhetzel** [comment]
Any updates on adding this term?

**Comment by LCCarmody** [comment]
added MAXO_0001472
