### ISSUE TITLE
NTR: Gastrostomy Tube Procedure

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/MAxO#328]
NTR: gastrostomy tube procedure

parent: MAXO:0000132 specific technique endoscopy

**note**: NCIT has a parent 'gastrointestinal endoscopy', would you want to add that to MAxO?

def: A procedure to insert a tube for feeding into the stomach.
NCIT:C157864

xref: NCIT:C157864

cc @lopierra
needed for INCLUDE

**Comment by LCCarmody** [comment]
Probably have to break this out into 2...' g-tube (synonym) placement' and 'g-tube usage'? Also J-tube, and GJ-tubes.

**Comment by pnrobinson** [comment]
Usually endoscopy means you are looking through a tube at something, and thus gastrostomy tube feeding is not endoscopy. NCIT is probably wrong here. 
Possibly it would be enough just to have one term called gastrostomy tube, since placement and usage probably always go together?

**Comment by LCCarmody** [comment]
Oh, yes...i agree. it should be in a different hierarchy. The reason I break them apart is because placement is by a surgeon and usage is often by a patient at home. they have different complications.  I've gone through those with my husband.

**Comment by pnrobinson** [comment]
I see what you mean, that makes sense

**Comment by nicolevasilevsky** [comment]
thanks @LCCarmody and @pnrobinson!

**Comment by twhetzel** [comment]
Any updates on adding this term?

**Comment by LCCarmody** [comment]
Following up on this term: @twhetzel @nicolevasilevsky what do you mean by this term?
This is not an endoscopy, (as discussed above).  
Do you mean placement of g-tube? That term is currently in MAXO (MAXO:0001346). If that's the case, we can close this ticket and start a new ticket for the terms below.

Do you mean as a method of food intake?
Possibly that could be added as a branch 'nutrition intake by feeding tube'? sibling to parenteral nutrition intake?

Should there also be 'feeding tube maintenance' branch? I am not sure where that would be. @pnrobinson

**Comment by nicolevasilevsky** [comment]
hi @LCCarmody, I probably asked for this for something for INCLUDE and I am no longer working on this project and I don't remember the context now. :) 

From what I wrote above, I think placement of g-tube is what I meant, so I agree that this ticket can be closed. 

thanks!
