### ISSUE TITLE
NTR: Digestive System Surgery

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/MAxO#329]
NTR: digestive system surgery

Parent: MAXO:0000004 surgical procedure

Def: Surgery performed on any part of the digestive system.
NCIT:C15330

xref: NCIT:C15330

cc @lopierra
needed for INCLUDE

**Comment by twhetzel** [comment]
Any updates on adding these terms?

**Comment by LCCarmody** [comment]
added new surgery by site pattern. Updated or added several new terms. This term will be available after next release.
