### ISSUE TITLE
NTR: sign language and lip reading

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/MAxO#330]
@LCCarmody would these terms make sense for MAxO?

- sign language
- lip reading (syn: speechreading)

Not sure what the best parent would be? Maybe MAXO:0000950 supportive care? Maybe a new grouping class like communication therapy?

needed for INCLUDE
cc @lopierra

**Comment by LCCarmody** [comment]
honestly, I'm not sure this is within scope of MAXO. I know we set up a broad set of treatments, but these are skills. I'll have to think about this.

**Comment by pnrobinson** [comment]
Possibly signing training or something like that?

**Comment by nicolevasilevsky** [comment]
The data that is being annotated in the INCLUDE project is uses sign language or lip reading. So maybe this is not in scope for MAxO? I agree, it's more like a skill.

cc @lopierra

**Comment by LCCarmody** [comment]
Closing ticket as out of scope
