### ISSUE TITLE
NTR: dentues

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/MAxO#331]
ntr: dentues

parent: 'dental and oral agent therapy'

def: 
An appliance used as an artificial or prosthetic replacement for missing teeth and adjacent tissues. 
NCIT:C63720

xref:
NCIT:C63720

needed for INCLUDE
cc @lopierra

**Comment by LCCarmody** [comment]
Probably need additional terms, like:
dental implantation, crown placement, bridge placement. Any others?

**Comment by nicolevasilevsky** [comment]
not that I can think of off the top of my head

**Comment by twhetzel** [comment]
Any updates on adding these terms?

**Comment by LCCarmody** [comment]
Hi... this is the same issue as earlier ticket. Is this 'fitting of dentures' or denture usage?
I think this is the fitting of dentures and how I plan to move forward.
As mentioned above, there are many, many dental terms that are required.

As this would be dental therapy(?) there doesn't exist a branch for this.
but suggestions:
therapy on the oral cavity
 -dental surgical procedure
 - occlusal rehabilitation
 -  periodontic therapeutic procedure
 - dental implantation/prosthodontic procedure (is this exact synonym?)
 --dental bridge placement/fixation of dental bridge
 --dental crown placement/crown attachment
  - fitting of dental products
 --fitting of  removable dentures
 ---fitting of removable dentures
--fitting of retainers

Many other dental procedures are preventative.

**Comment by LCCarmody** [comment]
added terms. closing.
