### ISSUE TITLE
NTR: Pull-through procedure and Ostomy surgery

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/MAxO#332]
**pull-through procedure**
def: Surgical removal of part of the large intestine that is missing nerve cells, and reconnection of the healthy part of the large intestine to the anus. This is the definitive operation for Hirschsprung disease. The surgeon then connects the healthy part of the large intestine to the anus.
Source: https://www.niddk.nih.gov/health-information/digestive-diseases/hirschsprung-disease/treatment

**ostomy surgery**
def: Surgical creation of a stoma and connection of the stoma to the large or small intestine. After ostomy surgery, waste will leave the body through the stoma.
source: https://www.niddk.nih.gov/health-information/digestive-diseases/hirschsprung-disease/treatment

maybe this is a better def from NCIT:
Surgical creation of an opening in an organ.
NCIT:C15290

synonyms:
ostomy
surgical construction of a stoma

xref:
NCIT:C15290

Needed for INCLUDE
cc @lopierra

**Comment by nicolevasilevsky** [comment]
related to https://github.com/monarch-initiative/MAxO/issues/286

**Comment by LCCarmody** [comment]
sorry for the long delay!

added several ostomy terms (new branch) and added pull-through procedure terms. Will be available at next realease

**Comment by lopierra** [comment]
Thanks @LCCarmody !
