### ISSUE TITLE
Is MAxO is suitable home for specific clinical outcome assessments?

### ISSUE THREAD

**Issue by matentzn** [monarch-initiative/MAxO#335]
We are currently building a vocabulary for [clinical outcome assessments](https://www.fda.gov/about-fda/clinical-outcome-assessment-coa-frequently-asked-questions) (COA), which include terms like:

- MFM-32 Domain 3 max score
- MFM-32 Total score
- Supine rolls to prone
- Supine sit up
- Seated on chair or wheelchair pencil reach
- Seated on chair or wheelchair pencil draw
- Standing with support maintaining standing position
- Standing with support raises one foot for 10 seconds

This can become quite detailed.

We are creating ROBOT templates and doing all the curation ourselves, so our question is: Is MAxO a suitable home for these terms? Should we work with you to get them in? If so, under which parent class would these go? 

We have submitted the same inquiry to the [OBI](https://github.com/obi-ontology/obi/issues/1586) ontology. The goal is to determine which ontology is the better fit, so that, moving forward, we have a standard place for COAs.

**Comment by LCCarmody** [comment]
Since MAxO does include tests to assess the patient, my inclination is that these terms can fit in MAxO. This would likely be in a branch of techniques with 'physical therapy evaluation' (MAXO_0000920), but we would need to build out the branch further to accommodate.

**Comment by peupeubangbang** [comment]
This is great @matentzn @LCCarmody 

For my own ref, a good place for cerebral palsy related clinician observations that didn't fit under HPO: 
obophenotype/human-phenotype-ontology#7278 
obophenotype/human-phenotype-ontology#7279 
obophenotype/human-phenotype-ontology#7280 
obophenotype/human-phenotype-ontology#7281 
obophenotype/human-phenotype-ontology#7282

**Comment by LCCarmody** [comment]
@peupeubangbang We will have to further investigate terms and a suitable branch. Thanks for your input.

**Comment by ramonawalls** [comment]
Thank you for the information, @LCCarmody . We are already using MAXO for a number of tests that show up in our data. I think OBI provides a better model for our most common use case, though, because we are specifically interested in triplifying patient level data that is the outcome of the different COAs and functional tests, and OBI provides a model for doing so. I plan to request the new COA terms in OBI, but if they will be useful to your community as well, they could be imported to MAXO.

**Comment by LCCarmody** [comment]
Closing as not being added (currently). Good luck.
