### ISSUE TITLE
NTR: Reproductive technology treatment/procedure

### ISSUE THREAD

**Issue by peupeubangbang** [monarch-initiative/MAxO#340]
I'm sure this is already on the cards was just thinking where these sorts of procedures would go in the branch. I think assisted **reproductive technology treatment/procedure** (as opposed to fertility treatment) is a good broader term so those procedures that aren't related to fertility (e.g. disease inheritance issues like gonadal mosaicism or mitochondrial replacement therapy/donation) can also fall under it (but still have **fertility treatment** as a synonym).

Assisted reproductive technology (ART) treatment is the terminology used by US CDC and in Australia (e.g. we have a 'Reproductive Technology Treatment' Register in Western Australia). The only problem with the current definition is that normally ART excludes anything to do with sperm only, i.e. only includes procedures where eggs and embryos are involved. I've left the definition blank for now in case I find a better one.

NCIT branch currently has [Reproductive Technique](https://www.ebi.ac.uk/ols/ontologies/ncit/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FNCIT_C19166&lang=en&viewMode=All&siblings=false) (e.g. [artificial insemination](https://www.ebi.ac.uk/ols/ontologies/ncit/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FNCIT_C16739&lang=en&viewMode=All&siblings=false) is a child term) sitting above [Assisted Reproductive Technology](https://www.ebi.ac.uk/ols/ontologies/ncit/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FNCIT_C93282&lang=en&viewMode=All&siblings=false). However NCIT have some embyro involved procedures (e.g. [ICSI](https://www.ebi.ac.uk/ols/ontologies/ncit/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FNCIT_C185482&lang=en&viewMode=All&siblings=false)) under that so based on the definition I think NCIT could use some reorganising, so I don't think MAxO should copy it.

I'm wondering if this should be separate to the obstetrics and gynecology branch, but child terms could be linked where it needs to be (e.g. link to the prenatal genetic testing involved in ART, like preimplantation genetic testing or genetic carrier screening).

We have a very experienced ART researcher in house who has reviewed and cleaned ART registry data before. If you like I could ask them to come up with a suggested branch of child terms to fall under this NTR @LCCarmody ?

**NTR:** Reproductive technology treatment
**Synonyms:** Reproductive technology procedure, ART, ART treatment, ART procedure, fertility treatment, fertility procedure
**Definition:** 
**Parent term:** Therapeutic procedure MAXO:0000002
**Xrefs:** NCIT:C93282, MESH:D027724

**Comment by LCCarmody** [comment]
Thanks for the ticket! Yes, this branch needs to be added. Definitely, if you know someone with the expertise and willingness to give their time, I am happy to listen and defer to their background knowledge.  Any additional input is welcome.

**Comment by LCCarmody** [comment]
sorry for the long delay. I don't know that I will be able to build out the branch, but suggesting the definition "are used to aid in achieving pregnancy conception in individuals who are having difficulty doing so spontaneously. "PMID: [35015434](https://pubmed.ncbi.nlm.nih.gov/35015434)

**Comment by LCCarmody** [comment]
I am adding fertility treatment as a broad synonym
