### ISSUE TITLE
NTR: Orchiopexy

### ISSUE THREAD

**Issue by peupeubangbang** [monarch-initiative/MAxO#342]
**NTR:** Orchiopexy
**Synonyms:** Orchidopexy, testicular fixation, fixation of testis
**Definition:** A surgical procedure to move a testis into the scrotum.
**Parent term:** Surgical procedure MAXO:0000004
**Xrefs:** SNOMEDCT_US:85419002, NCIT:C111066
**HPO link (if you link to phenotype):** HP:0000028, HP:0100813
**PMID:** 32809739

**Comment by LCCarmody** [comment]
Term MAXO_0001477. Will be available in next release
