### ISSUE TITLE
NTR: treatment with coagulating factor

### ISSUE THREAD

**Issue by sabrinatoro** [monarch-initiative/MAxO#343]
NTR: treatment with coagulating factor
(synonym: treatment with clotting factor)

**List of coagulating factors:** 

name | synonym | synonym | synonym
-- | -- | -- | --
factor I | fibrinogen |   |  
factor II | prothrombin |   |  
factor III | tissue factor | tissue thromboplastin |  
factor IV | ionized calcium | Ca++ |  
factor V | proaccelerin | labile factor |  
factor VI |   |   |  
factor VII | stabilizing factor | proconvertin | stable factor
factor VIII | antihemophilic factor A | FVIII |  
factor IX | Christmas factor | plasma thromboplastin component |  
factor X | Stuart-Prower factor |   |  
factor XI | plasma thromboplastin antecedent |   |  
factor XII | Hageman factor |   |  
factor XIII | fibrin-stabilizing factor |   |  

**references for the coagulation factors:** 
https://www.ncbi.nlm.nih.gov/books/NBK507850/
PMID:29939627
https://www.rnceus.com/coag/coagpro.html

**Note:** 
Though not reported as a coagulating factor, **von Willebrand factor (VWF)** is also often used for the treatment of hemorrhagic disease. 
Maybe this new term should be called "treatment with factors involved in coagulation" ? This way, we could include other factors such as VWF,

Also needed: 
the combination treatment: VWF/FVIII
(from https://www.ncbi.nlm.nih.gov/books/NBK7014/ "Intravenous infusion of VWF/FVIII clotting factor concentrates")

**Comment by LCCarmody** [comment]
added term under coagulant agent therapy already present. Will not have time to add all the separate factors, but hoping this suffices.

**Comment by pnrobinson** [comment]
@sabrinatoro 
adding for factors VIII and IX and vWF.
Replacement Rx for the other factors is not something commonly used in the clinic AFAIK. If there is a specific need, please open a new issue with PMID reference.
