### ISSUE TITLE
Phenopacket import option on the cards for treatabolome database?

### ISSUE THREAD

**Issue by peupeubangbang** [monarch-initiative/MAxO#346]
Hi @LCCarmody I know this isn't strictly MAxO but saw you were on the group involved in treatabolome.

Do you happen to know if a phenopacket import option is on the cards or has been discussed by yourself and Peter? 

I saw their DB presentation and thought it could definitely speed up import/adding MAxO, HPO, HGNC, HGVS, MONDO/ORDO/OMIM etc

**Comment by LCCarmody** [comment]
I know it has been discussed but I don't believe there has been any effort on implementation--though I admit it has been awhile since I've been to their meetings. They are currently trying to schedule one for October.  I could ask at that meeting (if it gets scheduled!)

**Comment by LCCarmody** [comment]
feel free to email me 'Leigh.Carmody at jax dot org' and I can pass along notes/info after the meeting.
