### ISSUE TITLE
Deprecation errors

### ISSUE THREAD

**Issue by LCCarmody** [monarch-initiative/MAxO#35]
ERROR	deprecated_class_reference	MAXO:0000273	rdfs:label	obsolete Gastrointestinal agents, other	
ERROR	deprecated_class_reference	MAXO:0000273	owl:deprecated	true^^http://www.w3.org/2001/XMLSchema#boolean

**Comment by matentzn** [comment]
Fixed now?

**Comment by LCCarmody** [comment]
This was fixed. Closing.
