### ISSUE TITLE
Janus kinase inhibitor treatment

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/MAxO#357]
synonym JAK inhibitor treatment

def: Treatment with an agent that inhibits the activity of one or more of the Janus kinase family of enzymes (JAK1, JAK2, JAK3, TYK2), thereby interfering with the JAK-STAT signaling pathway in lymphocytes.

Also add annotation
OMIM: 614162 
PMID: 30092289  (TREATS)

**Comment by LCCarmody** [comment]
added MAXO:0009096
