### ISSUE TITLE
accidental axiom in MAxO

### ISSUE THREAD

**Issue by balhoff** [monarch-initiative/MAxO#359]
MAxO includes the axiom:

[inheres in](http://purl.obolibrary.org/obo/RO_0000052) rdfs:subClassOf [radioactive](http://purl.obolibrary.org/obo/PATO_0001741)

I don't know how it got there, but it should be deleted.

Thanks @hlapp.

**Comment by LCCarmody** [comment]
I have no idea how/when that happened. WIll take care of it ASAP.
Thank you.
