### ISSUE TITLE
ophthalmic diagnostic procedure and children

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/MAxO#363]
ophthalmic diagnostic procedure
-- A diagnostic procedure to evaluate the structure and/or function of the eye and visual system.

children
--- fundoscopy: a visualization of the fundus of the eye including the retina and optic nerve with a fundoscope, a device that projects light through the pupil of the eye and visualizes the fundus with magnification.
(No NCIT id, note that Ophthalmoscopy is NOT a synonym)
-- optical coherence tomography. Def: is a noninvasive imaging technique and provides highresolution, cross-sectional images of the retina, the retinal nerve fiber layer (RNFL) and the optic nerve head. With axial resolution in the 5-7 micrometer range, it provides close to an in-vivo ‘optical biopsy’ of the retina. OCT employs light from a broadband light source, which is divided into a reference and a sample beam, to obtain a reflectivity versus depth profile of the retina. The light waves that are backscattered from the retina, interfere with the reference beam, and this interference pattern is used to measure the light echoes versus the depth profile of the tissue in vivo (PMID:23429598).
-- gonioscopy (syn. slit-lamp gonioscopy) def: an examination of the anterior chamber of the eye with a lens that is placed against the eye as a part of a slit-lamp examination

maybe a few other terms from https://www.ebi.ac.uk/ols/ontologies/ncit/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FNCIT_C38060&lang=en&viewMode=All&siblings=false

vision assessment
[Eye Movement Measurement](https://www.ebi.ac.uk/ols/ontologies/ncit/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FNCIT_C38060&lang=en&viewMode=All&siblings=false#)
[Slit-lamp Examination](https://www.ebi.ac.uk/ols/ontologies/ncit/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FNCIT_C38060&lang=en&viewMode=All&siblings=false#)

**Comment by LCCarmody** [comment]
I'm adding terms. Can you find definitions for fundoscopy and ophthalmoscopy? All searches say they are synonymous. Even PubMed identifies them as the same (although I cannot find the term in MeSH).
