### ISSUE TITLE
hand radiograph procedure

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/MAxO#366]
analogous to other terms
Also upper limb radiograph procedure

**Comment by LCCarmody** [comment]
additional radiograph terms:
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:////Users/carmol/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip.htm">
<link rel=File-List
href="file:////Users/carmol/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



maxo_id | maxo_label
-- | --
MAXO:0035001 | hand radiograph procedure
MAXO:0035002 | intraoral radiograph procedure
MAXO:0035043 | upper limb radiographic procedure



</body>

</html>
