### ISSUE TITLE
Remove subClassOf A and R some B pattern

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/MAxO#367]
It's best to break down axioms like this:

```owl
MAXO_0010115 SubClassOf
'nutrition intake avoidance'
 and ('avoided food' some 'calcium atom')
```

into

- `MAXO_0010115 SubClassOf 'nutrition intake avoidance'`
- `MAXO_0010115 SubClassOf and ('avoided food' some 'calcium atom')`

**Comment by LCCarmody** [comment]
Hmmm. I am not sure I understand the distinction (though, of course, I defer to your knowledge!). 

I have never tried to add 2 axioms to one DOSDP pattern. @matentzn Does this work?

**Comment by matentzn** [comment]
Yes, absolutely. Here is an example with more than one: https://github.com/obophenotype/bio-attribute-ontology/blob/master/src/patterns/dosdp-patterns/entity_attribute.yaml

@cmungall It seems to me this is a bit of an oversight of the `relax` command though..
