### ISSUE TITLE
inheres_in SubClassOf radioactive

### ISSUE THREAD

**Issue by matentzn** [monarch-initiative/MAxO#368]
This is a major error that merrits a quick new release :)

See:

https://github.com/EnvironmentOntology/environmental-exposure-ontology/issues/244

I love the fact that `inheres in` is classified as `radioactive`. But that needs to be fixed asap!

**Comment by LCCarmody** [comment]
but...I already fixed this...@balhoff pointed this out to me and I fixed it. I thought? Where is it coming from?

https://github.com/monarch-initiative/MAxO/releases/tag/v2022-11-22

**Comment by matentzn** [comment]
I just refreshed the ecto import and it is still there:

```
<!-- http://purl.obolibrary.org/obo/RO_0000052 -->

    <owl:Class rdf:about="http://purl.obolibrary.org/obo/RO_0000052">
        <rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/PATO_0001741"/>
    </owl:Class>
```

We will drill down where this comes from today.

**Comment by LCCarmody** [comment]
Fixed issue (hopefully for the last time!) Closing. Will be in next release.
