### ISSUE TITLE
Update MAXO OBO registry data

### ISSUE THREAD

**Issue by matentzn** [monarch-initiative/MAxO#369]
We should update the MAXO OBO Registry data

@LCCarmody 

Can you make a PR here and make sure that stuff like license (should be CC-BY 4.0) is updated?

https://github.com/OBOFoundry/OBOFoundry.github.io/blob/master/ontology/maxo.md

**Comment by LCCarmody** [comment]
updated
https://github.com/OBOFoundry/OBOFoundry.github.io/pull/2235
