### ISSUE TITLE
DOSDP specification

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/MAxO#376]
@matentzn @LCCarmody 
biopsy by type has this:

classes:
  biopsy: OBI:0002650
  diagnostic procedure: MAXO:0000003

but ct_by_)type has this

classes:
  ct: MAXO:0000571
  location: owl:Thing

Should we be using UBERON instead of owl:Thing?

**Comment by matentzn** [comment]
Good catch @pnrobinson! This wont change anything practically, but yes, I think from a documentation standpoint the location should be narrowed to Uberon:anatomical entity.

**Comment by LCCarmody** [comment]
will try to narrow soon

**Comment by LCCarmody** [comment]
changed the other 12 patterns where I did the same. fixed with #378
