### ISSUE TITLE
Think when changed to ODK, annotations labels got switched?

### ISSUE THREAD

**Issue by LCCarmody** [monarch-initiative/MAxO#38]
Not sure, but many of the definitions labels are now labeled as 'disease_annotation'.  These should all be changed to 'definition'.

Also, not sure if this was ODK or a user error, but all 'creator' annotations need to be changed to 'created_by'.

Also, I am a little confused, but there is the annotation  'database_cross_reference' and 'database_cross_reference (MAXO:0000024). I know that must have been something I made before ODK and I assume we should change to 'database_cross_reference'?

I assume this won't happen again now that it is migrated to the ODK? @matentzn 

- 'disease_annotation' -> 'definition'

- 'creator' -> 'created_by'

-  'database_cross_reference (MAXO:0000024)' -> 'database_cross_reference'

**Comment by matentzn** [comment]
The ODK would never ever change something in maxo-edit.owl, so this should be a user error. Lets address all these tickets in the next meeting. I notices also that the pattern is currently broken, so re-creating the definitions should not work at all.. In any case, lets put this on the agenda :)

**Comment by nicolevasilevsky** [comment]
@LCCarmody and @matentzn should I work on this ticket or should I wait until you two have met and discussed this?

(@LCCarmody I am working on #29 now)

**Comment by matentzn** [comment]
@nicolevasilevsky anything edit file related would be appreciated; just let us know what you find regarding this ticket.

**Comment by nicolevasilevsky** [comment]
@matentzn I'm not sure what you mean. Should I go ahead and fix these annotations in the edit file?

**Comment by nicolevasilevsky** [comment]
I am editing right now, so I'll fix these issues as I come across them

**Comment by LCCarmody** [comment]
I think that's good. I will assume that all lowercase terms have been fully edited for all of these items.

**Comment by matentzn** [comment]
Ok lets be a bit careful here.. @nicolevasilevsky dont fix anything biopsy and MRI related; we need to fix those on the level of the patterns. Anything else is good to go! (if you fixed biopsy and MRI stuff it does not matter, but these changes will be overwritten).

**Comment by nicolevasilevsky** [comment]
Got it - sounds good. I fixed the capitalization for biopsy terms (changed to lowercase) but have not touched the annotations, so I won't do that, and I'll fix it for other terms. Thanks @matentzn

**Comment by nicolevasilevsky** [comment]
I think I'm done updating all the annotations (except for biopsy and MRI terms, as Nico said not to do so). @LCCarmody do you want to double check and then close this ticket if everything looks good?

**Comment by LCCarmody** [comment]
Looks good. Will close after discussion with @matentzn tomorrow.

**Comment by LCCarmody** [comment]
We can close.
