### ISSUE TITLE
Need to add 'created_by' and 'dc:date' annotations to biopsy_by_location and MRI_by_location patterns

### ISSUE THREAD

**Issue by LCCarmody** [monarch-initiative/MAxO#39]
To be in line with HPO editors' guidelines, all ontology entries must have 'created_by' and 'dc:date' annotations added. I am not entirely sure how to add these to the pattern.

I assume I would add a column in the tsv file for 'created_by' and one for 'dc:date' and then add variable info in the yaml file.
I think we should do it this way in case someone else wants to add additional terms using the pattern.
@matentzn ?

**Comment by matentzn** [comment]
Just add the two columns for now, and start curating them; we will adjust the pattern to add this information in the next meeting. Note that currently, there is no way to annotate axioms with the the patterns approach (only classes), so you can say:

MAXO:001 created by Leigh
MAXO:002 dateCreated 09.09.2019

but you cannot say:
(MAXO:001 definition "A definition") <- created by Leigh. This would be a more complex issue requiring coordination with Jim Balhoff.

**Comment by LCCarmody** [comment]
Revisiting this looking at the 'avoidfoodintake' pattern.  Not really sure what has happened, but at least the date is not the same from the [tsv ](https://github.com/monarch-initiative/MAxO/blob/master/src/patterns/data/manual/avoidance_of_food_intake.tsv)file as for MAXO_0010000.  
Also needed are an rdsf:comment field, and has_exact_synonym field.
