### ISSUE TITLE
MAXO:0035050	spine radiography (maxolyzer)

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/MAxO#391]
MAXO:0035050	spine radiography

**Comment by LCCarmody** [comment]
same issue as #399. I assume because it is an X-ray, you would want to use 'vertebral column' for the Uberon (and not spinal cord)?

**Comment by pnrobinson** [comment]
X-rays are not good for spinal cord, but are good for the bony vertebral column. Spine MRI is better for the spinal cord

**Comment by LCCarmody** [comment]
added term.
