### ISSUE TITLE
MAXO:0035054	protein glycosylation assay

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/MAxO#395]
MAXO:0035054	protein glycosylation assay
def: biochemical investigation of amount or type of glycosylation of proteins.

**Comment by LCCarmody** [comment]
same as https://github.com/monarch-initiative/MAxO/issues/501 will use this number as it is the first.

**Comment by LCCarmody** [comment]
added this ID/term via template. Did not use other ID.
