### ISSUE TITLE
MAXO:0035056	spine MRI

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/MAxO#399]
MAXO:0035056	spine MRI

**Comment by LCCarmody** [comment]
spine was already requested with ID MAXO:0035014. see #382 will not use this number.

**Comment by LCCarmody** [comment]
One question: Do you want this to be vertebral column or spinal cord? There doesn't appear to be an UBERON term that encompasses both.

**Comment by pnrobinson** [comment]
The spine MRI gives information about both the spinal cord and the vertebral column. It is probably ok to use the uberon term for spinal cord since this the organ that the spinal MRI is often better at visualizing

**Comment by LCCarmody** [comment]
Added term as spinal cord MRI under MAXO:0035014.
