### ISSUE TITLE
Teriparatide

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/MAxO#403]
Teriparatide 

label:  recombinant human parathyroid hormone treatment
definition: Treatment with recombinant human parathyroid hormone treatment. This treatment is used to stimulate bone formation, increase bone mass, and reduce the risk of vertebral and nonvertebral fractures

https://pubmed.ncbi.nlm.nih.gov/35993038/

**Comment by pnrobinson** [comment]
Also add annotation to Osteoporosis-pseudoglioma syndrome (OMIM:259770)
https://pubmed.ncbi.nlm.nih.gov/35993038/
once we have the new term

**Comment by LCCarmody** [comment]
added term and closing issue.
