### ISSUE TITLE
MAXO:0035063	EEG-EMG jerk-locked averaging

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/MAxO#406]
MAXO:0035063	EEG-EMG jerk-locked averaging
definition: A technique that combines EEG and EMG to assess myoclonus. The technique use electromyography (EMG) electrodes for the arms or legs, and correlates averaged EEG responses with EMG bursts used as a trigger. 
PMID: 1464676

parent --  sibling of EEG and EMG

**Comment by LCCarmody** [comment]
added via template
