### ISSUE TITLE
MAXO:0035066	somatosensory evoked potential assessment

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/MAxO#409]
MAXO:0035066	somatosensory evoked potential assessment

Measurement of somatosensory evoked potentials (SEPs), which reflect the electrical activity of the brain that results from the stimulation of touch. SEP monitoring may be employed intraoperatively to identify, and ideally, avoid impending permanent damage to neurologic structures. PMID: [31335078](https://pubmed.ncbi.nlm.nih.gov/31335078)

**Comment by LCCarmody** [comment]
added via template
