### ISSUE TITLE
MAXO:0035068 natural killer cell function  test

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/MAxO#411]
MAXO:0035068 natural killer cell function  test

def: An assay of the physiology of natural killer (NK) cells. For instance, NK cells (or total peripheral blood mononuclear cells) are isolated from whole blood and mixed with fluorescently labeled K562 target cells and the proportion of lysed (killed) K562 cells is determined by flow cytometry.

**Comment by LCCarmody** [comment]
added via template
