### ISSUE TITLE
remove text mining codes

### ISSUE THREAD

**Issue by kingmanzhang** [monarch-initiative/MAxO#44]
My old codes are used to find NCIT or other ontology terms from GeneReviews articles. I think they are only useful for us and should not be in this folder. We should delete them or move them to a separate folder that are dedicated to text mining. This one is reserved for ontology itself.

**Comment by LCCarmody** [comment]
@pnrobinson were discussing this yesterday.  I think we (@pnrobinson @hannahblau) should start a new repo for text mining specifically for MAxO.  I think this info could go there until someone decides what to do with it?  What do you think?

**Comment by kingmanzhang** [comment]
+1

**Comment by kingmanzhang** [comment]
Let's move codes to https://github.com/monarch-initiative/MAxO-TM
close it now.
