### ISSUE TITLE
Pick a suitable class for COB alignment

### ISSUE THREAD

**Issue by matentzn** [monarch-initiative/MAxO#441]
https://www.ebi.ac.uk/ols4/ontologies/cob/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FOBI_0000011

**Comment by matentzn** [comment]
Which class should medical action subclassed under?

**Comment by LCCarmody** [comment]
'planned process'?

**Comment by matentzn** [comment]
I am happy with that if there is nothing more specific!

**Comment by LCCarmody** [comment]
Well, I am a little confounded with 'completely executed planned process'. It seems to me that even if it isn't completely executed, it could still be a medical action. 

There are assays that are medical actions, but not everything is an assay.  So, I think it is planned process, but I am not completely sure.

**Comment by matentzn** [comment]
Yes, I think I share your uncertainty! I would say we stick with planned process for now!

**Comment by LCCarmody** [comment]
SInce it is (sorta) implemented, could I close this ticket?

**Comment by matentzn** [comment]
If medical action is subClassOf planned process this can be closed. Importing cob specifically may not be necessary.

**Comment by LCCarmody** [comment]
It is child of COB_0000082 which is planned process. Assuming this is fine, I will close. If there is an issue, please let me know.
