### ISSUE TITLE
Biopsy of muscle tissue and biopsy of muscle are redundant

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/MAxO#442]
Probably remove Biopsy of muscle tissue  and keep biopsy of muscle.
If we do decide the keep biopsy of muscle tissue, then the definition needs work: 
Removal of tissue from the muscle tissue.

**Comment by LCCarmody** [comment]
obsoleted biopsy of muscle and replaced with biopsy of muscle tissue. df:about="http://purl.obolibrary.org/obo/MAXO_0000386">
        <obo:IAO_0100001 rdf:resource="http://purl.obolibrary.org/obo/MAXO_0000387"/>
        <rdfs:label>obsolete biopsy of muscle</rdfs:label>
