### ISSUE TITLE
Automatically generated labels for the biopsy terms

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/MAxO#443]
The definitions of the biopsy terms should be revised. Firstly, those terms that contain "tissue" in the item label sound funny.
Removal of tissue from the adipose tissue.

Also, and more importantly, "Removal of tissue from X" is wrong. It should be

Removal and examination of tissue, cells, or fluids from X for the purpose of detecting or characterizing disease.

**Comment by LCCarmody** [comment]
Will change after critical release. I think changing the text definition will change all the issues, but once I do, we can look to see if labels or definitions need to be overridden.
