### ISSUE TITLE
MAXO:0035090	cholescintigraphy

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/MAxO#447]
MAXO:0035090	cholescintigraphy
def:An imaging procedure used to visualize liver, gallbladder and bile ducts following intravenous injection of iminodiacetic acid, a radioactive tracer that is taken up by gall-producing cells and secreted into the bile, following which imaging is performed by a gamma camera.

synonym: Hepatobiliary iminodiacetic acid scan; HIDA scan

**Comment by LCCarmody** [comment]
hepatobiliary iminodiacetic acid (HIDA) scan seems to be the more common usage (NCI, mayo clinic, CPT). Should we use that as the label and cholescintigraphy as the synonym?
