### ISSUE TITLE
Issue running make templates

### ISSUE THREAD

**Issue by LCCarmody** [monarch-initiative/MAxO#464]
needed to 'replace' terms. When I ran `Sh run.sh make templates`, got an odd message. I don't think I've seen it before. Would the terms be replaced when running a release (have not tried yet).

![Screen Shot 2023-02-21 at 4 04 59 PM](https://user-images.githubusercontent.com/26067008/220459196-952a27b1-ec81-45ef-a102-71ae02820ae5.png)

Not an immediate issue, but will need it for next release. Thanks in advance.

**Comment by matentzn** [comment]
Oops my bad.. added back. I erroneously though the command was redundant.
