### ISSUE TITLE
MAXO:0035102	water deprivation test

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/MAxO#471]
MAXO:0035102	water deprivation test
The water deprivation test, also known as the indirect water deprivation test should potentially be able to distinguish the various forms of DI. Deprivation of water intake should allow patients with primary polydipsia to concentrate their urine while those with central or nephrogenic DI continue to excrete dilute urine. Administration of desmopressin (Deamino-8-D-arginine vasopressin), the synthetic analogue of AVP, after water deprivation should help with differentiating patients with central DI from those with nephrogenic DI as the former should be able to concentrate the urine once the deficient action of AVP is replaced with desmopressin, while the latter should not show a significant response due to end-organ resistance to the action of AVP or its analogues. PMID:30779536

**Comment by LCCarmody** [comment]
added via template
