### ISSUE TITLE
MAXO:0035110	gustatory testing

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/MAxO#499]
MAXO:0035110	gustatory testing
def: A medical test that evaluates the ability to taste. The tests are either chemical or electrical in nature. Chemical testing uses the natural stimuli and chemical tastants (sweet, sour, salty, bitter, and umami) to assess taste, whereas electrical testing adopts electrical currents applied directly to the surface of the tongue. Other investigations are employed in the assessment of gustatory dysfunction, such as certain imaging techniques, though these are not as useful in quantifying taste disorders.
PMID:33620811

probably this should be a child of diagnostic procedure

**Comment by LCCarmody** [comment]
added via template
