### ISSUE TITLE
Template solution for construction of MAO

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/MAxO#5]
Let's start with the "avoid" items
Let's develop a template that will take
a. name (e.g., alcohol)
b. xref (if available, e.g., from ChEBI, http://www.ebi.ac.uk/chebi/searchId.do?chebiId=30879)
c. parent (one of the upper level terms that we have manually added to the mao-edit.owl file; or, one of the other terms in the csv file, e.g., fasting and prolonged fasting/starving)
Use a template to transform this information into OWL classes
Then import the file into the main mao/edit.owl file and check, Q/C it

**Comment by LCCarmody** [comment]
This is now a duplicate. Will close.
