### ISSUE TITLE
MAXO:0035111	hepatobiliary iminodiacetic acid scan

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/MAxO#500]
MAXO:0035111	hepatobiliary iminodiacetic acid scan
synonyms - cholescintigraphy, hepatobiliary scintigraphy, HIDA scan
def: An imaging procedure in which a radioactive tracer is injected intravenously. The tracer is taken up by bile producing cells and subsequently travels with the bile into the gallbladder and through the bile ducts to the small intestine. THe hepatobiliary iminodiacetic acid (HIDA) scan can be used to visualize the liver, gallbladder and bile ducts.

**Comment by pnrobinson** [comment]
Not sure if the parent should be MAXO_0000595 (OLS is not showing the label or definition) or simply diagnostic procedure

**Comment by LCCarmody** [comment]
1. This is the same request as #447, though cholescintigraphy was the label previously. We decided  hepatobiliary iminodiacetic acid scan was the best label previously. Which ID would youlike to use? MAXO:0035111 or MAXO:0035090?
2. Use new OLS. The old OLS is no longer updating. MAXO_0000595 is radiograph imaging procedure.
3. new OLS is here: https://www.ebi.ac.uk/ols4/
