### ISSUE TITLE
MAXO:0035114	immune cell function assay

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/MAxO#503]
MAXO:0035114	immune cell function assay

def: measurement of peripheral blood lymphocyte response following stimulation to assess the degree of functionality of the cell-mediated immune response. A variety of tests exist to measure intracellular ATP levels, proliferation, and other functional responses.

I think this could go under clinical laboratory procedure, but with time we might want to have a branch such as cell function assay -- platelet aggregation would be another example.

**Comment by LCCarmody** [comment]
added via template. https://docs.google.com/spreadsheets/d/1ZKk3cFQNYAXsNWbpI-ScaIm3OHx2Jtpco3Y1aNX7gZM/edit#gid=0
