### ISSUE TITLE
MAXO:0035115	diffusion weighted cerebral MRI

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/MAxO#504]
MAXO:0035115	diffusion weighted cerebral MRI
A type of cerebral magnetic resonsnace (MR) imaging that measures random Brownian motion of water molecules within each voxel of imaged brain tissue.

parent: MRI of brain

**Comment by LCCarmody** [comment]
added via template. https://docs.google.com/spreadsheets/d/1ZKk3cFQNYAXsNWbpI-ScaIm3OHx2Jtpco3Y1aNX7gZM/edit#gid=0
