### ISSUE TITLE
MAXO:0035116	oncologist evaluation

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/MAxO#505]
MAXO:0035116	oncologist evaluation

**Comment by LCCarmody** [comment]
This term already exists as 'medical oncologist evaluation'...mainly called medical oncologist because of abms.org website. Will add oncologist evaluation as a synonym.
please use MAXO_0000691 for future use.

**Comment by pnrobinson** [comment]
I think in this context, "Medical" oncologist can be the synonym, people will search first under plain "Oncologist evaluation"!
