### ISSUE TITLE
MAXO:0035118	cardiac catheterization

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/MAxO#507]
MAXO:0035118	cardiac catheterization
A procedure in which a catheter (thin hollow tube) is threaded into the heart via a large blood vessel, generally with contrast dye being injected through the catheter to visualize the heart chambers and coronary arteries.

**Comment by LCCarmody** [comment]
added via template. https://docs.google.com/spreadsheets/d/1ZKk3cFQNYAXsNWbpI-ScaIm3OHx2Jtpco3Y1aNX7gZM/edit#gid=0
