### ISSUE TITLE
MAXO:0035120	cardiac auscultation

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/MAxO#509]
MAXO:0035120	cardiac auscultation
def: Investigation of heart sounds with a stethoscope.
parent- clinical assesssment

**Comment by LCCarmody** [comment]
added via template. https://docs.google.com/spreadsheets/d/1ZKk3cFQNYAXsNWbpI-ScaIm3OHx2Jtpco3Y1aNX7gZM/edit#gid=0
