### ISSUE TITLE
ntr: artificial nutrition and hydration

### ISSUE THREAD

**Issue by laurenechan** [monarch-initiative/MAxO#53]
parent: life support
label: artificial nutrition and hydration
definition: Artificial nutrition and hydration is a medical treatment that allows a person to receive nutrition (food) and hydration (fluids) when they are no longer able to take them by mouth. Artificial nutrition and hydration is given to a person who for some reason cannot eat or drink enough to sustain life or health.
Reference: www.caringinfo.org/files/public/brochures/ArtificialNutritionAndHydration.pdf  Info from Caring Info National Hospice and Palliative Care Organization

We can likely use enteral nutrition, parenteral nutrition, and intravenous fluids as some kind of synonym to this as these are the same therapies, just different timing and at this point this is the term used when choosing to continue or withdraw from "life support". There are lots of pieces to choose when it comes to life support, not sure if we'd like to expand to include a few of those terms here.

**Comment by laurenechan** [comment]
parent: life support
label: resuscitation 
definition: The measures applied for the restoration a person to life and/or consciousness. The act of resuscitation includes such components as artificial respiration and cardiac massage. 
reference: NCIT_C50822

same thing here, we don't have to expand on life support, but there are significantly different choices that come with continuing or d/c'ing life support techniques. we can also get more specific in resuscitation techniques if we like.

**Comment by pnrobinson** [comment]
We should probably not try to model all of the different choices, since nobody will look at an ontology to figure out whether resuscitation is needed!

**Comment by laurenechan** [comment]
@pnrobinson Ok! So then question along the same note as to how much detail may be warranted, for things like nutrition support (enteral and parenteral nutrition), do we want want to discuss particular approaches to either of those or leave them as a large class? For example, you can do bolus, continuous, or trophic/trickle feeding with enteral nutrition. Are those important for us to model or too detailed?

**Comment by pnrobinson** [comment]
@laurenechan Well, I have been wrong many times before, but currently I would see the main use case of MAxO in improving the findability of literature for rare disease treatments, and not actually in providing ontology terms for the precise recommendations (We do not have resources for guideline development! Nor the expertise!). And so I am thinking that we will show a rare disease on a website (HPO, Mondo, others) and use the MaXO to help parse and organize papers that are relevant. Clinicians would grok the contents from the abstract and it would be confusing to have too much detail....

**Comment by LCCarmody** [comment]
FWIW, ClinGen was very interested in MAxO and interested in providing published guidelines for (rare) disease.  I am not sure that it would go into that much detail.  My inclination is to add this term to the 'nutritional intervention' branch and go no deeper.  A comment could be made about the types.  There are terms MAXO_0000090 'enteral tube feeding' and MAXO_0000114 'parenteral nutrition' present--so this would be a sibling?

I was thinking the branch that could be most useful for @laurenechan  to build out is 'dietary intervention' and/or a list of food/nutritional substance to avoid in rare disease. 

One big help would be to identify prospective terms and then identify Foodon terms related. With @matentzn help, I started a 'Medical action avoidance' pattern to build out terms.  I would like to start a 'Food avoidance' pattern (and a 'Behavior avoidance pattern', etc.).

Maybe we could chat about this?

**Comment by laurenechan** [comment]
Sounds good, I think I may still have some considerations for what is currently in the 'nutrition intervention' branch just to make the word choice more accurate, but maybe we can chat about that to if there was a particular reason for the phrasing currently being used. 
As for the list of foods to avoid etc, I'll start parsing through that list ( I think it's on another ticket) if that sounds like the next path to go down.
