### ISSUE TITLE
Cryopreserved amniotic membrane

### ISSUE THREAD

**Issue by Sukramg** [monarch-initiative/MAxO#536]
**Cryopreserved amniotic membrane**

Corneal Dystrophy, Epithelial Basement Membrane   OMIM:121820 MONDO:0007375
PMID 30809089

Encourages regrowth in vital, damaged areas	ProKera®	Acute attack
Failed lubrication and punctal occlusion

Cryopreserved amniotic membrane is a treatment option for certain eye diseases and conditions, particularly those affecting the cornea and conjunctiva. The amniotic membrane is a thin layer of tissue that lines the inside of the amniotic sac during pregnancy and is usually discarded after childbirth. However, it can also be collected and processed for medical use.

To create cryopreserved amniotic membrane, the membrane is collected from the placenta and processed to remove any blood or other tissues. The membrane is then cryopreserved, which involves freezing the tissue to very low temperatures to preserve its structure and biological properties.

Cryopreserved amniotic membrane can be used as a patch on the surface of the eye to promote healing and reduce inflammation in conditions such as corneal ulcers, burns, and recurrent erosion syndrome. The membrane contains a variety of growth factors and anti-inflammatory substances that can help to promote tissue regeneration and reduce scarring.

The membrane is typically applied to the surface of the eye during a minor surgical procedure, and the patient is monitored for any adverse effects or complications. The membrane is usually left in place for several days to several weeks, depending on the severity of the condition and the patient's response to treatment.

Cryopreserved amniotic membrane is generally safe and well-tolerated, although some patients may experience mild discomfort or irritation during the healing process. It is important to follow the ophthalmologist's instructions for use and care of the membrane to ensure its effectiveness and prevent complications such as infection or further damage to the eye.

**Comment by LCCarmody** [comment]
adding amniotic membrane transplantation for ophthalmology as this is a medical action ontology.

**Comment by LCCarmody** [comment]
thank you for all of your suggestions.
