### ISSUE TITLE
MMP inhibitors 

### ISSUE THREAD

**Issue by Sukramg** [monarch-initiative/MAxO#537]
MMP inhibitors 

Corneal Dystrophy, Epithelial Basement Membrane   OMIM:121820 MONDO:0007375
PMID 30809089

Works to prevent the breakdown of vital collagen and hemi- desmosomes by stunting the production of the enzyme MMP-9 | Systemic tetracyclines (eg, doxycycline 50 mg BID) | Failed lubrication and punctal occlusion

Matrix metalloproteinase (MMP) inhibitors are a type of medication used in the therapy of certain eye diseases, particularly those affecting the cornea. MMPs are enzymes that play a role in the breakdown of the extracellular matrix, a complex network of proteins and other substances that provide structural support to the cornea and other tissues in the body.

In certain eye diseases, such as corneal ulcers, MMPs can become overactive, leading to excessive breakdown of the extracellular matrix and damage to the cornea. MMP inhibitors work by blocking the activity of these enzymes, helping to reduce inflammation and promote healing of the cornea.

MMP inhibitors can be administered topically, as eye drops or ointments, or systemically, as oral medications or intravenous infusions. They may be used alone or in combination with other therapies, such as antibiotics or anti-inflammatory medications, depending on the underlying condition and its severity.

MMP inhibitors have shown promise in the treatment of a variety of corneal diseases, including corneal ulcers, keratitis, and recurrent erosion syndrome. They have also been studied in the context of corneal transplantation, where they may help to improve graft survival and reduce the risk of rejection.

However, MMP inhibitors can have potential side effects, such as irritation, dryness, and blurred vision. They may also interfere with wound healing in some cases, so their use should be carefully monitored by an ophthalmologist. Additionally, their long-term safety and efficacy have not been fully established, and further research is needed to determine their optimal use in the treatment of eye diseases.

**Comment by LCCarmody** [comment]
added tMMP inhibitor therapy. closing issue now, but I am also tagging with annotation for future usage
