### ISSUE TITLE
duplication: low fat diet intake //  low fat dietary intake 

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/MAxO#539]
http://purl.obolibrary.org/obo/MAXO_0000766 (MAXO):
        low fat diet intake in Ontobee: [MAXO](https://ontobee.org/ontology/MAXO?iri=http://purl.obolibrary.org/obo/MAXO_0000766)
    http://purl.obolibrary.org/obo/MAXO_0010003 (MAXO):
        low fat dietary intake in Ontobee: [MAXO](https://ontobee.org/ontology/MAXO?iri=http://purl.obolibrary.org/obo/MAXO_0010003)

**Comment by LCCarmody** [comment]
fixing (near) duplicate synonym. Close this ticket, but will need a larger discussion about what to do with all 'avoid' terms in the futute
