### ISSUE TITLE
For consistency, add http://orcid.org/ before orcid #

### ISSUE THREAD

**Issue by LCCarmody** [monarch-initiative/MAxO#54]
@laurenechan @nicolevasilevsky 

I know there has been some back and forth about this in other ontologies, but I propose that we include 'http://orcid.org/ before our orcid ids.

That is how protege records 'created_by' fields.  Issue is that for some xrefs, there is 0000-0002-7463-6306 is listed and does not link out to orcid.  I think it should be 'http://orcid.org/0000-0002-7463-6306'.  Does that work for everyone?

**Comment by nicolevasilevsky** [comment]
yes, that sounds good!

**Comment by pnrobinson** [comment]
In HPO we have ORCID:0000-0002-7463-6306 and no URLs...

**Comment by LCCarmody** [comment]
Actually, we have both. We also have HPO:name and several other types of xrefs.
The way we are supposed to be using protege, it automatically adds the url for created_by

**Comment by LCCarmody** [comment]
Will revisit later if need be. Closing for now.
