### ISSUE TITLE
NTR farnesyltransferase inhibitor

### ISSUE THREAD

**Issue by megankraus** [monarch-initiative/MAxO#543]
New Term Label: farnesyl transferase inhibitor
Definition: Farnesyl transferase inhibitors are small-molecule inhibitors that selectively inhibit farnesylation of a number of intracellular substrate proteins such as Ras. Farnesyl transferase inhibitors represent a new class of agents that target signal transduction pathways responsible for the proliferation and survival of diverse malignant cell types.
Definition source: https://www.medchemexpress.com/Targets/Farnesyl%20Transferase.html 
Synonym exact: none
Cross Reference: NCI Thesaurus Code:  C1856
Parent term: enzyme inhibitor agent therapy MAXO:0000648
OCIDID: 0000-0003-4830-7530

**Comment by LCCarmody** [comment]
added ntr. It is available in the latest release. Will see if Mike will update POET

Thanks so much for your help

**Comment by megankraus** [comment]
Great!!! Thank you so much! 

It’s been such a pleasure working with you

Megan
