### ISSUE TITLE
Deep Sclerectomy

### ISSUE THREAD

**Issue by Sukramg** [monarch-initiative/MAxO#549]
# 137760 GLAUCOMA, PRIMARY OPEN ANGLE; POAG

Varga Z, Shaarawy T. Deep sclerectomy: safety and efficacy. Middle East Afr J Ophthalmol. 2009 Jul;16(3):123-6. doi: 10.4103/0974-9233.56223. PMID: 20142976; PMCID: PMC2813598.
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2813598/

Deep sclerectomy is a surgical procedure used to treat glaucoma, a condition that can damage the optic nerve and lead to vision loss. This procedure involves creating a small flap in the sclera, the outermost layer of the eye, and removing a portion of the trabecular meshwork, the area of the eye responsible for draining aqueous humor, the fluid that circulates inside the eye.

During deep sclerectomy, a small incision is made in the conjunctiva, the membrane that covers the white part of the eye, and a thin flap is created in the sclera. A small opening is then made in the trabecular meshwork, and a portion of the meshwork is removed using a special surgical tool. The flap in the sclera is then repositioned, and a small amount of viscoelastic material may be used to maintain the shape of the space created by the procedure.

Deep sclerectomy is designed to improve the outflow of aqueous humor and lower intraocular pressure, which can help to prevent damage to the optic nerve. The procedure can be performed alone or in combination with cataract surgery, a common procedure to remove the natural lens of the eye.

**Comment by LCCarmody** [comment]
deep sclerectomy was recently added MAXO:0000958

Let me know if it needs more context.

Thanks.

**Comment by LCCarmody** [comment]
closing ticket. Sorry I have taken my time. I will try get to your tickets soon.
