### ISSUE TITLE
"Oxygen Therapy" may need more specific terminology

### ISSUE THREAD

**Issue by laurenechan** [monarch-initiative/MAxO#55]
Looking at the term oxygen therapy (parent: therapeutic intervention) I was uncertain as to whether or not this was a mention of supplemental O2 support (i.e. through nasal cannula) or something like hyperbaric oxygen therapy for wound healing. Separate terms may be needed for each should we like to include them both.

**Comment by LCCarmody** [comment]
I tend to agree with you and think these could be useful terms.  I do not think we should go into more detail beyond this (at the moment).

**Comment by LCCarmody** [comment]
Added numerous terms to this and changed this label to 'supplemental oxygen therapy'  I've merged it and it will be available for the next release.
Closing
