### ISSUE TITLE
NTR: behavioral nutrition intervention and regulated nutrition intervention

### ISSUE THREAD

**Issue by LCCarmody** [monarch-initiative/MAxO#56]
‘Behavioral nutritional intervention’ and ‘regulated nutritional intervention’ under ‘Nutritional intervention’ (MAXO_0000009) based on the WHO https://www.who.int/elena/intervention/en/

**Comment by laurenechan** [comment]
Based on WHO terminology, this likely should be 'nutrition Intervention' (no -al at the end) and similarly 'behavioral nutrition intervention' and 'regulated nutrition intervention' (without -al in either). Can certainly also add exact synonyms for these terms with -al.
