### ISSUE TITLE
angiography procedure term replaced by

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/MAxO#576]
angiography procedure
https://www.ebi.ac.uk/ols4/ontologies/maxo/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FMAXO_0001259

was obsoleted and "term_replaced" by therapy, but this is a diagnostic procedure and should be "term_replaced" by
angiography
https://www.ebi.ac.uk/ols4/ontologies/maxo/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FMAXO_0001259

**Comment by LCCarmody** [comment]
Maybe the issue is too long ago, but it appears to be fixed as it is in the diagnostic branch. closing.
