### ISSUE TITLE
New synonyms to Consider alterations of ‘enteral tube feed’, ‘total parenteral nutrition’ and ‘gavage’ to improve the accuracy of word choice

### ISSUE THREAD

**Issue by LCCarmody** [monarch-initiative/MAxO#58]
Consider alterations of ‘enteral tube feed’, ‘total parenteral nutrition’ and ‘gavage’ to improve the accuracy of word choice

**Comment by LCCarmody** [comment]
@matentzn and @pnrobinson ,  @laurenechan has made some good observations about changing term labels and moving the labels to synonyms.  Do we need to worry about the obsoletion of term labels yet?

**Comment by matentzn** [comment]
IMHO we should never ever worry about obsoletion of labels. This is total overkill for vocabulary maintenance; that is why we have identifiers. We use obsoletion only in cases where we want to discourage the use of a word altogether (dwarfism case in HP). So my two cents is: go ahead and change if you maintain the original labels as synonyms! :)

**Comment by pnrobinson** [comment]
Definitelt agree! Please just change the primary label and add the original primary label as an exact synonym. Nothing else is required!

**Comment by laurenechan** [comment]
I've made a few changes to reflect what I find to be more accurate terms, PR has been made. 

Regarding total parenteral nutrition (TPN), I still find this to be a somewhat inaccurate term choice. TPN includes full and complete nutrition provided intravenously, whereas parenteral nutrition can be provided as specific macronutrients (i.e. just carbs and protein) or can be providing only part of the nutrition required (i.e. 50% of needs).
Without getting into the weeds, I think it would be more accurate to reorganize this as:
superclass: nutrition intervention
class: parenteral nutrition
subclasses: total parenteral nutrition (same NCIT term as we have now) and parenteral therapeutic nutrition supplementation (another NCIT term, not well defined currently) or some other variety indicating only partial needs provided through IV. 
What do you all think on this? @pnrobinson @LCCarmody

**Comment by LCCarmody** [comment]
Just to clarify, you would change 'enteral tube feed' to 'parenteral nutrition'?  I support that based on what you are saying. Also, total parenteral nutrition should be a child term.
  I am not sure about 'parenteral therapeutic nutrition supplementation'.  Is that what it is typically called?  If it is just NCIT that has a term, then I might suggest 'parenteral supplementation' or 'parenteral nutrition supplementation' as the label with 'parenteral therapeutic nutrition supplementation' as an exact synonym and cross reference to NCIT.  

I do not think we want to go deeper than that.

**Comment by laurenechan** [comment]
To clarify, I would be changing 'total parenteral nutrition' --> 'parenteral nutrition' with 'total parenteral nutrition' as a child term. 'Enteral tube feed' (or enteral nutrition as rec in the PR) would stay a separate term as they are separate feeding modalities. I think this was reflected in the PR, but if that doesn't seem clear I can make alterations.

Typically I'd call it 'partial parenteral nutrition' or 'supplemental parenteral nutrition', but yes just some term to provide differentiation as to how much is provided (full or partial of needs).

**Comment by LCCarmody** [comment]
I think the hierarchy to what you are saying is fine, but it depends if you are physically doing it the way that you just described.   I have an issue with changing the label to mean something else and then recreating the same term as a child with a new MAXO number.  

Even though I don't think there are (any?) users yet, theoretically it could mess up someone who is trying to find the term MAXO_0000114 total parenteral nutrition and find now it is 'parenteral nutrition' and the term they are actually looking for is a different number.  

Looking at the pull request (and admittedly, I am not great at PR), i think this is what you are doing.   Could you make the new term the 'parenteral nutrition' and move the MAXO_0000114 as a child?  Do you know how to make new terms? Have a range of MAXO numbers?  We can have a call this afternoon if not.

**Comment by pnrobinson** [comment]
I agree -- one should not change the meaning of an existing term by giving it a new label --

**Comment by laurenechan** [comment]
Ok, that makes total sense! From the sense of the PR that has been put in (branch: lec_6.19_2), this does not include any changes to the class status or label of total parenteral nutrition at this time other than adding synonyms. 

I think creation of a new superclass (and new number etc) definitely makes the most sense. I think I know how to make new terms, but do not have a range of numbers yet. Can get on a call this afternoon if that is easiest!
