### ISSUE TITLE
dcterms:creator or created_by?

### ISSUE THREAD

**Issue by LCCarmody** [monarch-initiative/MAxO#580]
@matentzn 
This is related to HP question, but I am seeing the results in MAXO.

I automatically loaded up with the OBO annotators plugin. I **think** I had it on my last machine, too, BUT all the created by are http://www.geneontology.org/formats/oboInOwl#created_by vs.  this  version set up, which is http://purl.org/dc/terms/creator.

should I change all to dcterms:creator? (I assume, yes, in a text editor, but I wanted to confirm).

https://github.com/obophenotype/human-phenotype-ontology/issues/9721

**Comment by matentzn** [comment]
We should be using `dcterms:creator` or `dcterms:contributor` all the way, no more `http://www.geneontology.org/formats/oboInOwl#created_by`!

**Comment by LCCarmody** [comment]
@matentzn 

What should I do about DOSDP files? Currently, 'created_by: oio:created_by'
Is there an equivalent one for dcterms:creator? Also, where would I look?

**Comment by matentzn** [comment]
I would try to simply replace `created_by: oio:created_by` https://github.com/monarch-initiative/MAxO/blob/master/src/patterns/dosdp-patterns/avoidance_of_food_intake.yaml#L20 with `created_by: dcterms:creator`?

**Comment by LCCarmody** [comment]
Well, sure, but everytime I run 'definitions' wouldn't it add the wrong creator annotation? Or at very least, new terms would?
(I can't test anything as I don't have the computer set up to test what happens)

**Comment by matentzn** [comment]
I dont think it should! If `created_by: dcterms:creator` is in the DOSPD, it will use the dcterms:creator! Only that. Which is what you want, right?

**Comment by LCCarmody** [comment]
oh, misunderstood. I will change. thx.

**Comment by LCCarmody** [comment]
Last question, is there an easier way to do this? 
Tried variations of `-type f -exec  sed -i "s/'created_by: oio:created_by'/'created_by: dcterms:creator'/g" {} \;`

but this gives an error `sed: 1: "./protein_measurement_u ...": invalid command code .
sed: 1: "./mri_by_location.yaml": invalid command code .
sed: 1: "./therapeuticprocedure_ ...": invalid command code .
sed: 1: "./swab_by_location.yaml": invalid command code .
sed: 1: "./screening_for_phenoty ...": invalid command code .
sed: 1: "./protein_measurement_s ...": invalid command code .`...

**Comment by matentzn** [comment]
:D hahah.. ask ChatGPT, that is too advanced for me. or maybe on slack in the random channel

**Comment by LCCarmody** [comment]
Ha. After a small argument with ChatGPT, I got it to work. FTR: 
`find . -type f -exec sed -i '' 's/created_by: oio:created_by/created_by: dcterms:creator/g' {} \;`

**Comment by matentzn** [comment]
🤣 

Great!
