### ISSUE TITLE
Add MAXO annotation pipeline

### ISSUE THREAD

**Issue by matentzn** [monarch-initiative/MAxO#583]
Similar to what you see in hp.Makefile (`hpoa` goal), we need a goal in MAXO for pulling the up to date annotations. The rough recipe is

```
#!/bin/bash

PASSWORD=password
# Release process involves moving accepted annotations (HP & MAXO) by an admin in POET to official annotations
curl https://poet.jax.org/api/v1/export/release?key=<PASSWORD>
# Get the MAXO annotation file
curl https://poet.jax.org/api/v1/export/maxo?unstable=false
# Move or rename file with release date.
```

Can we add a goal like:

```
maxoa:
    curl https://poet.jax.org/api/v1/export/release?key=<PASSWORD>
    # Get the MAXO annotation file
    curl https://poet.jax.org/api/v1/export/maxo?unstable=false
    # Move or rename file with release date.
```

To maxo.Makefile?

**Comment by LCCarmody** [comment]
We are building this into MAXO proper and not maxo-annotations?

**Comment by matentzn** [comment]
Yes, because we want to piggy back on MAXO versioning system and not create another versioning system that's separate. Same as we do with HPO!

**Comment by pnrobinson** [comment]
@matentzn so you mean that we will retrieve the annotations from POET and the annotation repo and make a combined release following Q/C? That would be awesome

**Comment by matentzn** [comment]
Yes!

**Comment by LCCarmody** [comment]
I think I will need help with the specifics

**Comment by matentzn** [comment]
No need, @LCCarmody - @iimpulse knows exactly what needs to be done. we have done it before!

**Comment by LCCarmody** [comment]
@iimpulse Can you take care of this?

**Comment by LCCarmody** [comment]
Can we close this ticket? or help/reminder of what I need to add to maxo docs?

**Comment by matentzn** [comment]
@LCCarmody do you have a link to the "How to create a MAXO release" doc?

**Comment by LCCarmody** [comment]
Yes, but it does need to be updated. Not sure the best way to handle the maxo-annotations bit. 
current is [HERE](https://github.com/monarch-initiative/MAxO/wiki/Release)

**Comment by matentzn** [comment]
I updated the instructions. Can you run a test release, improve the instructions along the way (I wrote them from memory)? If they are good and you have successfully created a release with the MAXOA annotations attached to the GitHub release, you can close this issue! Thank you!
