### ISSUE TITLE
Update wiki

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/MAxO#587]
https://github.com/monarch-initiative/MAxO/wiki/DOSDP-pattern-creation-and-edits

@LCCarmody  @matentzn 

can we delete the struck through text here? 
e.g.
RUN RELEASE

**Comment by matentzn** [comment]
Of course! I removed that specific instance. Just delete whatever you don't need but for the future:

don't use wikis.. Just use the normal mkdocs pattern we use everywhere. This way, we have histories of our documentation and can retrieve past edits if ever necessary.. No need to make a move now!

**Comment by LCCarmody** [comment]
Thanks. Closing issue. Will change to mkdocs in the future.
