### ISSUE TITLE
NTR: gross motor therapy

### ISSUE THREAD

**Issue by twhetzel** [monarch-initiative/MAxO#599]
ntr: gross motor therapy

parent: physical therapy, MAXO:0000011

def: Gross motor therapy is designed to help individuals improve their use of large muscles and the coordination of the arms, legs, and the entire body.

synonym: gross motor skills therapy

needed for INCLUDE
cc @lopierra

**Comment by LCCarmody** [comment]
added MAXO_0001505. Will be available next release
