### ISSUE TITLE
NTR: sensory therapy

### ISSUE THREAD

**Issue by twhetzel** [monarch-initiative/MAxO#600]
ntr: sensory therapy

parent: occupational therapy, MAXO:0001351

def: Sensory therapy is designed to help children with sensory-processing problems using play-oriented therapy and may include using equipment such as swings, trampolines, and slides.

synonym: sensory integration therapy

source: https://www.healthychildren.org/English/health-issues/conditions/developmental-disabilities/Pages/Sensory-Integration-Therapy.aspx

needed for INCLUDE
cc @lopierra

**Comment by LCCarmody** [comment]
I think the label should be sensory integration therapy and not use 'sensory therapy'. 
Sensory integration therapy seems to be the way it is described by many groups and I think this may be confused with sensory re-education/training therapy and sensorimotor therapy. These terms aren't currently in MAxO, but if present, would be under physical therapy.

It may be reasonable to set up a hierarchy for sensory types of therapy that is outside of PT/OT separation, but that would not be implemented immediately.

Do you agree?

**Comment by LCCarmody** [comment]
adding as sensory integration therapy. Will be available in next release.
