### ISSUE TITLE
NTR: Hirschsprung disease surgery

### ISSUE THREAD

**Issue by twhetzel** [monarch-initiative/MAxO#606]
ntr: Hirschsprung disease surgery

parent: colectomy, MAXO:0001042

def: A surgical procedure where a portion of the colon that is missing nerves to control the muscles responsible for moving stool through the colon is removed.

synonym: pull-through surgery 

needed for INCLUDE
cc @lopierr

**Comment by LCCarmody** [comment]
MAXO_0000977 pull-through procedure already exists. We can add further synonyms. I prefer not to use a disease name in the label. Maybe a narrow synonym or comment that it is used for this disease?

**Comment by pnrobinson** [comment]
I agree with Leigh, I do not think it is a great idea to put the name of the disease in the term. The treatment is a partial or total colectomy, and the indication is Hirschsprung. Putting this in the comment sounds like a good idea (it is also not really a synonym)

**Comment by twhetzel** [comment]
Thanks @LCCarmody for pointing out that term. Adding a comment that it is used for this disease as you suggest would be helpful.
