### ISSUE TITLE
Possible excel-based issue in ORCID identifiers

### ISSUE THREAD

**Issue by cthoyt** [monarch-initiative/MAxO#610]
I extracted the list of all ORCID ids from MAXO and found the following:

```
0000-0001-7941-2962	maxo
0000-0001-7941-2963	maxo
0000-0001-7941-2964	maxo
0000-0001-7941-2965	maxo
0000-0001-7941-2969	maxo
0000-0001-7941-2974	maxo
0000-0001-7941-2978	maxo
0000-0001-7941-2979	maxo
```

These appear to be going in ascending order, which makes me think that someone grabbed and dragged a cell in an excel sheet, resulting in all of these. I searched the repo for where they show up, and it appears they proliferated to many places, so I'm not sure how to fix this. I guess they should all actually be referring to @LCCarmody's ORCID which is https://orcid.org/0000-0001-7941-2961

**Comment by LCCarmody** [comment]
That's exactly what happened! I thought I fixed these!  Will be updated in next release. Thanks for the catch.
