### ISSUE TITLE
NTR: Branch of methods of drug delivery

### ISSUE THREAD

**Issue by LCCarmody** [monarch-initiative/MAxO#617]
oral, parenteral (injected), sublingual, topical, otic, transdermal, nasal, ocular, rectal, vaginal are some of the methods.

Relates to #324 #512 #538, #554

**Comment by laurenechan** [comment]
Just adding another specific instance in which route of administration would be useful:

I was recently browsing for parenteral nutrient supplementation terms (e.g., intravenous phosphorus supplementation for hypophosphatemia). Currently in MAxO's 'nutrition supplementation' branch, a variety of nutrient supplements are included, but 'Nutrition supplementation' has a parent class of ' dietary intervention', indicating a GI based exposure to the nutrient being supplemented. Having a nonspecific class for 'X nutrient supplementation' and allowing for indication of a parenteral versus oral etc. route of administration would be useful to differentiate.
