### ISSUE TITLE
NTR: expand carrier screening terms

### ISSUE THREAD

**Issue by LCCarmody** [monarch-initiative/MAxO#623]
- [x]  preimplantation genetic testing, 
- [x] cell free fetal DNA, 
- [ ] and now less commonly things like integrated screening

**Comment by LCCarmody** [comment]
I agree that genetic carrier screening should be parent. This is just a note (to myself or others ;) ) to expand terms under genetic carrier screening. More research will need to be done. Any references you know of would be greatly appreciated.

**Comment by peupeubangbang** [comment]
No problem as far as expanded carrier screening including reproductive carrier screening this is probably helpful:

PMID: 30240948
PMID: 35334631
PMID: 31774570
PMID: 37086152
PMID: 36756860

**Comment by LCCarmody** [comment]
Thanks for your input

**Comment by LCCarmody** [comment]
added synonyms and cell free DNA testing. closing
