### ISSUE TITLE
Activate Travis: not enough Monarch permissions

### ISSUE THREAD

**Issue by matentzn** [monarch-initiative/MAxO#63]
https://travis-ci.org/organizations/monarch-initiative/repositories

Can someone like @pnrobinson activate travis for MAXO? I dont have the right permissions (and I dont want them :P)

**Comment by pnrobinson** [comment]
I do not know how to do that -- if somebody can tell me I will set it up though

**Comment by LCCarmody** [comment]
Maybe @cmungall or @drseb can lend a hand?

**Comment by LCCarmody** [comment]
@matentzn please write step-by-step actions

**Comment by drseb** [comment]
Can‘t you copy the travis.yml from hp or mp to maxo root folder??

**Comment by matentzn** [comment]
That is already the case; what needs to happen is this: 

1. Go to https://travis-ci.org/monarch-initiative/MAxO (log in)
2. Click on activate repository

I think that is it. Maybe you need to confirm a security dialogue. Dont know. Could you try that @drseb ?  Thanks!

**Comment by drseb** [comment]
done

**Comment by matentzn** [comment]
Perfect thanks seb. All works:
https://travis-ci.org/monarch-initiative/MAxO

@LCCarmody note travis fails now; so have fun fixing MAXO to make it pass!

**Comment by LCCarmody** [comment]
Quick question before we go: how can we get automatic emails if travis has failed?  Can we currently have it sent to the HP editors address (hpo-editors@googlegroups.com)--and then change it sometime in the future to a MAXO specific email?  Thx

**Comment by matentzn** [comment]
See https://github.com/monarch-initiative/MAxO/pull/70
