### ISSUE TITLE
Superclass/Graph Errors

### ISSUE THREAD

**Issue by iimpulse** [monarch-initiative/MAxO#630]
https://github.com/monarch-initiative/MAxO/blob/8939722039245e3a67926d41a9401e028f399d14/src/ontology/reports/maxo-base.owl-obo-report.tsv#L4

@LCCarmody @matentzn 

When deploying a new service with maxo-base.json. I've found that the terms in this file will not allow me deploy because we can't find the super/sub classes for these terms in the graph. Can we figure out whats going on here?

**Comment by matentzn** [comment]
This is a very confusing subject, sorry about that.. I will fix it without explaining it, but the problem was actually expected, and has to do with what a base file actually has been up until today - the "editors file". in maxo, the editors file is lacking thousands of subclass axioms.

**Comment by LCCarmody** [comment]
Thank you. I was about to start hunting for what the issue was.

**Comment by matentzn** [comment]
Should be fixed when @LCCarmody pushes the next release

**Comment by LCCarmody** [comment]
Trying to do a release to clean stuff up, but I am getting an error that I am not sure I understand. 
`PROFILE VIOLATION ERROR http://purl.obolibrary.org/obo/maxo.owl violates profile DL
For details see: http://robot.obolibrary.org/validate-profile#profile-violation-error
Use the -vvv option to show the stack trace.
Use the --help option to see usage information.
OWL 2 DL Profile Report: Ontology and imports closure NOT in profile. The following violations are present:
Use of reserved vocabulary for annotation property IRI: rdf:type [Declaration(AnnotationProperty(rdf:type)) in OntologyID(OntologyIRI(<http://purl.obolibrary.org/obo/maxo.owl>) VersionIRI(<http://purl.obolibrary.org/obo/maxo/releases/2024-02-02/maxo.owl>))]
make: *** [Makefile:174: reports/validate_profile_owl2dl_maxo.owl.txt] Error 1`
![Screenshot 2024-02-02 at 11 01 29 AM](https://github.com/monarch-initiative/MAxO/assets/26067008/7b437250-dd08-4407-aa26-689b57d93acd)

**Comment by matentzn** [comment]
argh.. I am sure it is due to https://github.com/FoodOntology/foodon/pull/293

@LCCarmody can you commit all files to a branch, make PR and I will implement a way around this.

Also, maybe email Damion about this PR and ask him if he has time to fix it, it causes me a huge headache.

**Comment by LCCarmody** [comment]
I believe all is fixed here. Made a new release. Closing this ticket.
