### ISSUE TITLE
Issue with undefined OBI and CHEBI terms in release

### ISSUE THREAD

**Issue by LCCarmody** [monarch-initiative/MAxO#637]
Two OBI IDs and one CHEBI ID are not defined in the release after release pipeline. The OBI IDs (see below) are both used in FoodOn axioms and the CHEBI term is used in MAXO axiom.  Setting up a ticket now to track this issue @matentzn 

Dear MAxO Team,
 
Hello. I am a doctoral student from the Bioinformatics Team at Shanghai Jiao Tong University. Recently, while using your MAxO files, I encountered some minor issues and would like to consult with you. In the latest version of MAxO, the relationships mention OBI:0000299, OBI:0000293, and CHEBI:32184, but these three entities are not defined throughout the entire file. I am not sure if this was overlooked during the compilation by your team, so I am reaching out to seek clarification.

**Comment by LCCarmody** [comment]
@matentzn After updating Chebi slim, I updated MAxO release, but I ended up with more undefined terms than before. This time I think they come in from Cell ontology. The OBI ones are still not fixed.
<img width="280" alt="Screenshot 2024-05-06 at 11 38 12 AM" src="https://github.com/monarch-initiative/MAxO/assets/26067008/3219374b-b611-4e11-94e2-6fba329be71e">
Not sure what to do.

**Comment by matentzn** [comment]
Can you provide a list of all the undefined classes? You mean these two MOD ones?

**Comment by LCCarmody** [comment]
Is there anyway to search for them?
The 'new' ones that I noticed are: MOD_00167, MOD_00818, and PR_000050567, BSPO_0000096
BSPO_0000097
BSPO_0000098
BSPO_0000099
BSPO_0000100
BSPO_0000102
BSPO_0000107
BSPO_0000108
BSPO_0000120
BSPO_0000121
BSPO_0000122
BSPO_0000123
BSPO_0000124
BSPO_0000126
BSPO_0001106
BSPO_0001107
BSPO_0001108
BSPO_0001113
BSPO_0001115
BSPO_0005001
BSPO_0015101

The persistent ones are COB_0000082,OBI:0000299, OBI:0000293


But given these are dispersed, I am not sure I have all of the ones that are undefined.
