### ISSUE TITLE
Consider additional child terms for 'dietary intervention'

### ISSUE THREAD

**Issue by laurenechan** [monarch-initiative/MAxO#66]
Currently the term 'dietary intervention' has 2 child classes, 'calorie restrictive diets' and 'nutritional supplementation'. 
To better address other dietary adaptations that may be recommended to patients that do not fall into these categories, we may consider the additional child term of 'non-calorie restrictive diets'. This could then have child classes such as low sodium diets, ketogenic diet and literally anything that does not have innate caloric restriction. An example here:
![option 1](https://user-images.githubusercontent.com/49169837/61080598-4659d080-a3da-11e9-8760-ba26b6d189de.png)

Secondly, we can also further classify the 'non-calorie restrictive diets' into subclasses such as 'macronutrient restricted diets', 'food group restrictive diets', 'micronutrient restrictive diets', and 'texture modified diets'. Each class can then have items fall into it, i.e. 'low carbohydrate diet' into 'macronutrient restricted diets'. An example here:
![option 2](https://user-images.githubusercontent.com/49169837/61080651-5ffb1800-a3da-11e9-878f-673087c2d94f.png)

As there are widely used dietary patterns that fall into the non-calorie restrictive category I feel this would allow for greater identification of these therapies within both the rare and common disease populations. I am also happy to build out some of the most commonly used diets as terms should we move forward with this.

One consideration, as there are diets that choose to reduce or eliminate pieces from the diet (i.e. gluten free), should we consider diverting some or all of these term types towards 'therapeutic nutritional avoidance'? Or do we offer the diet term 'gluten free diet' and separately offer the avoidance term 'gluten consumption avoidance'?

**Comment by LCCarmody** [comment]
Hi Lauren, I am currently building out the avoidance terms patterns. 
The first term in the pattern is 'gluten avoidance' --although others will be added. 
I don't have a strict policy of whether something should be 'avoided' or listed as 'low' nutrition, although it might be a good idea to define something.   

It could belong under both--by having multiple parentages in an ontology. I.e., Low sodium diet would have the exact synonym 'Sodium avoidance' and be a child of both 'dietary intervention' and 'nutrition avoidance'. 

This is relatively easy to do in protege, but I'd have to think about it (and ask @matentzn ) about how/if to do it with patterns.  

Also, I'd say: don't add the term 'non-calorie restrictive diet' because it doesn't make much sense as a term outside of the context of the ontology.  We can always add a different parent term later if needed.

**Comment by matentzn** [comment]
Is this a blocker or can this wait for our next MAXO call?

**Comment by LCCarmody** [comment]
It isn't super urgent--but @pnrobinson  wanted to be in on this discussion (if possible).  Issue is: I will be at ICBO July 30-Aug 2 and Peter will be on Vacation at exotic locals Aug 1-Aug 22.

**Comment by matentzn** [comment]
Shall we meet at our usual time coming Wednesday to do this?

**Comment by laurenechan** [comment]
Just to revisit the idea of adding 'dietary interventions' I wanted to note some therapeutic diets we may be interested in creating terms from. Any thoughts on the following or approaches we'd like to take to select which we might add?

"heart health"/cardiac diet (low sodium, low fat)
vegan (no animal products)
vegetarian (lacto, ovo, ovo-lacto, pescitarian)
celiac (primarily gluten free, but also a malabsorptive condition and may require additional nutrients)
ketogenic (high fat, mod protein, low carb)
exclusive *formula* feeding, dependent on condition may have unique formula selection (MSUD, galactosemia, etc)
carbohydrate controlled (would be a specific # of carbs, not sure if we want this lumped in with low carb etc.)
low purine (gout prevention/flare up reduction)
DASH (hypertension)
Dysphagia diet (multiple classes, associated with International Dysphagia Diet Standardisation Initiative)
Post-bariatric surgery diet (reduced capacity and may have induced malabsorption)
Anemia prevention/management diets (for all types)
Malabsorption condition diets (Cystic fibrosis, short bowel sydrome, celiac, ulcerative colitis etc)
Renal (some differences for CKD and ESRD)
Wound healing (increased protein and kcals, Vitamin A & C, zinc)
