### ISSUE TITLE
NTR: vegan diet

### ISSUE THREAD

**Issue by laurenechan** [monarch-initiative/MAxO#81]
In efforts to start filling out our dietary interventions category, I'll have a few different NTRs including the current one! I look forward to your feedback on inclusion. 

Parent: dietary intervention (MAXO:0000088) 
Label: vegan diet
Definition: A vegan diet is the total exclusion of any animal-derived substance including not only products where the animal has to be killed (meat and gelatin) but also dairy products, eggs, and other animal-based food ingredients.
Reference: PMID:27378750

**Comment by LCCarmody** [comment]
At the moment, this is not a medical recommendation.  Will close for now.
