### ISSUE TITLE
NTR: gluten free diet

### ISSUE THREAD

**Issue by laurenechan** [monarch-initiative/MAxO#83]
I know there was some discussion about an "avoidance of gluten" term, so let me know if this feels redundant.

Parent: dietary intervention (MAXO:0000088) 
Label: gluten free diet
 Broad synonym: wheat free diet, barley free diet, oat free diet, rye free diet, celiac diet?
Definition: A gluten free diet includes complete removal of gluten from the diet including foods with wheat, barley, rye, and gluten containing oat ingredients. A gluten free diet may lead to possible nutrient deficiencies (such as fiber and specific micronutrients) or nutrient excess (i.e. saturated fats).
Reference: PMID:28786929, PMID:27211234

so avoidance terms here may include those for gluten, rye, barley, wheat...

**Comment by LCCarmody** [comment]
See consolidated ticket. Closing
