### ISSUE TITLE
NTR: Ketogenic diet

### ISSUE THREAD

**Issue by laurenechan** [monarch-initiative/MAxO#84]
Parent: dietary intervention (MAXO:0000088) 
Label: ketogenic diet 
Narrow synonym: classic ketogenic diet, medium-chain triglyceride(s) (MCT) ketogenic diet, modified Atkins diet, and low glycemic index treatment
Definition: The ketogenic diet is a high-fat, low-carbohydrate, adequate-protein diet that mimics a fasting state, resulting in the substitution of ketone bodies as a source of energy. The ketogenic diet can be used to reduce recurrent epileptic seizures in individuals with intractable epilepsy. Intractable epilepsy is defined as epilepsy that failed to respond to three or more antiepileptic drugs.
Reference: PMID:28701250, PMID:27759811, PMID:23419562

**Comment by laurenechan** [comment]
So just trying to put into context some of the avoid/include terms here...

avoidance_of_food_intake  some  "excess carbohydrate consumption"
avoidance_of_food_intake  some  "excess protein consumption"

increase_food_intake (or whatever we choose for increase/include) some "excess fat consumption"
 ** not sure if excess fat consumption works here. Technically a super high fat diet (excess) but it does sound a little strange

Again, just trying to get some of the thoughts down and we can fine tune the wording as we determine our object properties and such

**Comment by LCCarmody** [comment]
Go ahead and add the term and textual definition. 

I think the logical definition would be (dietary intervention and (has_involved_medical_action some avoid_carbs) and  (has_involved_medical_action some eat_protein)) and (has_involved_medical_action_ some eat_fat)).  I need to work on some of the properties to add this,though.

**Comment by LCCarmody** [comment]
Will not create logical def at this point. Will follow up if needed.
