### ISSUE TITLE
NTR: exclusive formula feeding

### ISSUE THREAD

**Issue by laurenechan** [monarch-initiative/MAxO#85]
Parent: dietary intervention (MAXO:0000088)
 Label: exclusive formula feeding 
Exact synonym: EFF (abbreviation)
Definition: Exclusively feeding an infant formula in efforts to prevent allergic reactions, intolerances, or communication of diseases (i.e. HIV) through feeding human milk. 
Reference: PMID:23711175

**Comment by laurenechan** [comment]
avoidance_of_food_intake  some  "human milk consumption"

A concern for this, how can we describe literally all other foods that are not formula to put some kind of avoidance term in? Most use cases will be an avoidance of breast milk when looking at the definition, but it obviously limits food as well.

**Comment by LCCarmody** [comment]
I think we can leave it at that and add that into the textual definition.
Please keep in mind that we need this to be a suggestion for a specific disease. Look at GeneReviews for specific cases and wording.  For instance, only a handful of diseases call for avoiding breast feeding--but it is usually more complicated than that--like avoiding CMV-contaminated blood products.  There are some that require low amounts of galactose, but it is a limit breast feeding recommendation and use a low galactose formula.  Look for case examples.

**Comment by laurenechan** [comment]
From what I found in GeneReviews, the primary use cases here would include:
*Classic galactosemia and clinical variant galactosemia*, during infancy and early childhood, use of soy formulas (minimal galactose/lactose), restrict conventional formulas and breast milk

*ZAP70-Related Combined Immunodeficiency*: formula feed until mother’s CMV state is known

*Classic phenylketonuria*: will start low protein diet and Phe-free medical formula as soon after birth as possible (can also use into adulthood, but will introduce other foods)

While identifying the mother's CMV state could resolve such a feeding pattern, individuals w/ galactosemia and phenylketonuria likely will remain formula fed. I can also adapt the textual definition if we don't feel it quite applies to our use cases.
Maybe more like this?
*Exclusively feeding an infant formula for management of inborn metabolic errors or to reduce risk for communication of disease through feeding human milk.* 
References: PMID:23711175, PMID:26518046, PMID:20625932, PMID:26835392

Or are we looking to be more distinct with our terms? We can also scrap this definition and define avoidance of phenylalanine, avoidance of CMV contaminated milk, avoidance of lactose/galactose etc. instead.

**Comment by LCCarmody** [comment]
I think formula feeding should be added and I like your definition.

I think we should have avoidance of phenylalanine (phenylalanine-restriticted diet?), etc.

I think maybe we shouldn't bew as specific with CMV contaminated milk.  Maybe the label could be avoidance of CMV contaminated (bodily fluid) products? Use that term as a catch all with a comment that this could be blood, breast milk, etc.
