### ISSUE TITLE
Proposed logical definition for dietary intervention

### ISSUE THREAD

**Issue by laurenechan** [monarch-initiative/MAxO#86]
'nutrition intervention'
and ('dietary intervention' some '%s')
%s = dietary intervention terms (still building those out and making NTRs this week)

From my understanding, we've chosen to separate individual foods and full diet plans/dietary interventions, so we likely need the new object property 'dietary intervention' unless there appears to be another term that might fit appropriately. 

This feels super simple, am I totally missing something here??

**Comment by matentzn** [comment]
I would recommend not to use MAXO terms when defining dietary interventions. 

Lets look at it conceptually: what IS a dietary intervention in human terms?

**Comment by laurenechan** [comment]
In my mind you could consider dietary intervention to be any kind of alteration made specifically to dietary intake. For example, putting someone on a specific diet for their medical condition like a ketogenic diet. This would not, however, include any information on education/counseling, or recommendations that are feeding in a way other than by mouth.

**Comment by matentzn** [comment]
Mention this in our meeting later today; this is best discussed in person.

**Comment by laurenechan** [comment]
Okie dokie so if we look at this from the perspective of individual diets getting their own pattern of sorts to state the inclusions/exclusions indicated, would we need inclusion/exclusion terms for every single one of those items separate from the dietary term?

Also, from the call, it seemed as though we were not as interested in noting things in what I consider food group terms (i.e. fruit, grains, proteins) but rather in terms of nutrients (i.e. antioxidants or fiber). Are there any cases in which is would be allowable to incorporate a food group?

For example a vegan diet includes:
Dietary_intake_avoidance of meat, fish, poultry, gelatin, dairy, eggs, animal based food ingredients
Would these be allowable avoidance terms?

Just trying to get some guidelines here so I can start identifying inclusions/exclusions on my NTRs

**Comment by LCCarmody** [comment]
Are there diseases that specifically recommend no meat, fish, poultry?  Peter recommended using a small clinical book called Vademecum Metabolicum: Diagnosis and Treatment of Inborn errors of metabolism (by Zschocke and Hoffmann).  Ex. Phenylketonuria recommendation is a phenylalanine-restricted diet.

**Comment by laurenechan** [comment]
From an exclusively rare disease standpoint, I don't know that we are going to find specific recommendations for vegan/vegetarian diet patterns. From a common disease standpoint, it's a little more likely for us to see a wide range of options for a single diet. This means we may see some composition of vegan/vegetarian for things such as cardiovascular disease, chronic kidney disease, colorectal cancer, T2 diabetes etc. 

As I know we are more rare disease oriented at the time being, maybe it makes sense to hold off on some of these decisions until we want/need to include some of these diet terms that are more food group-y?

**Comment by pnrobinson** [comment]
Note that about 75% of processed foods include some form of animal products (yuck!). However, I am not sure we need to be this precise in our logical definition, and vegan diet is not (AFAIK) a typical medical intervention.

**Comment by LCCarmody** [comment]
Going to close this for now. Will open if we wish to be more granular with logical definitions.
