### ISSUE TITLE
NTR: texture modified diet

### ISSUE THREAD

**Issue by laurenechan** [monarch-initiative/MAxO#87]
Parent: dietary intervention (MAXO:0000088)
 Label: texture modified diet
Exact synonym: dysphagia diet, thickness modification of food and fluids
 Narrow synonym: texture modified food, thickened liquid, pureed food
Definition: Texture-modified foods and thickened drinks used to reduce the risks of choking and aspiration for individuals with oropharyngeal incoordination or dysphagia.
Reference: PMID:28343526, PMID:27913916

Use cases:
*Familial dysautonomia*: For infants, thickened formula and different-shaped nipples are useful in managing orophyaryngeal incoordination. 

FOXP2 gene deletion: PMID:27148578

States where dysphagia is common: *Spinocerebellar Ataxia, SYNE1 Deficiency, Woodhouse-Sakati Syndrome* just to name a few (many of the 100+ results in GeneReview mention texture modification for dysphagia)

**Comment by LCCarmody** [comment]
Yes, add this.
