### ISSUE TITLE
NTR: digestive enzyme supplementation

### ISSUE THREAD

**Issue by laurenechan** [monarch-initiative/MAxO#88]
Parent: dietary intervention (MAXO:0000088) 
Label: digestive enzyme supplementation 
Narrow synonym: pancreatic enzyme supplementation, pancreatic enzyme replacement therapy
Definition: Animal-based, plant-based, or microbe-derived enzyme supplementation used clinically in digestive and absorption disorders, particularly with regard to exocrine pancreatic insufficiency or other conditions associated with poor digestion including lactose intolerance.
Reference: PMID:19152478

Use cases:
Lactose intolerance, cystic fibrosis, malabsorption (general), pancreatitis, Total pancreatectomy with islet auto-transplantation (TPIAT), pancreatic exocrine insufficiency

**I wasn’t sure if this was most appropriate under ‘dietary intervention’ or as a ‘nutritional supplementation’. As these enzymes are not nutrients I was not sure they should fall in with other supplements that are distinct micro/macro nutrients.

**Comment by LCCarmody** [comment]
Added to the new spreadsheet. closing this ticket.
