### ISSUE TITLE
NTR: phenylalanine restricted diet

### ISSUE THREAD

**Issue by laurenechan** [monarch-initiative/MAxO#91]
Parent: dietary intervention (MAXO:0000088)
Label: phenylalanine restricted diet
Exact synonym: low phenylalanine diet
Definition: Dietary approaches avoid excessive phenylalanine consumption, including stringent dietary restriction of natural protein intake, and supplementation of amino acids other than phenylalanine by a chemically manufactured protein substitute.
Reference: PMID:20720592, PMID:20971365
Avoidance: phenylalanine containing foods or derivatives, artificial sweeteners, excess protein intake

Primary use cases:
Phenylketonuria, Tyrosinemia Type 1, potentially therapeutic for ochronosis from alkaptonuria

**Comment by LCCarmody** [comment]
Yes, add this.
