### ISSUE TITLE
NTR: galactose free diet

### ISSUE THREAD

**Issue by laurenechan** [monarch-initiative/MAxO#93]
Parent: dietary intervention (MAXO:0000088) 
Label: galactose free diet
Definition: Avoidance of breast milk, proprietary infant formulas containing lactose, cow’s milk, dairy products, casein or whey-containing foods, and medications with lactose and galactose for the management of classic galactosemia or clinical variant galactosemia.
Reference: PMID:20301691, PMID:20625932
Avoidance terms: lactose, galactose, dairy, casein, whey, human milk

I wasn't certain if this definition felt too infant oriented, obviously this is still present in adults so I was hoping for more encompassing.

**Comment by LCCarmody** [comment]
See the consolidated ticket. Closing.
