### ISSUE TITLE
NTR: branched chain amino acid restricted diet

### ISSUE THREAD

**Issue by laurenechan** [monarch-initiative/MAxO#95]
Parent: dietary intervention (MAXO:0000088)
 Label: branched chain amino acid restricted diet
Exact synonym: BCAA restricted diet
Definition: Dietary recommendations focused on reducing intake, catabolism and the accumulation of branched chain amino acids (BCAA) and their corresponding -ketoacids. 
Individual dietary recommendations may include restrictions on single or multiple BCAA
Reference: PMID:24881969
Avoid: excess branch chained amino acid intake, excess valine, isoleucine, leucine, alpha ketoacids
Include: low BCAA protein

Use cases: Maple syrup urine disease, branched chain alpha-ketoacid dehydrogenase [BCKDH] complex deficiency (type of Dihydrolipoamide Dehydrogenase deficiency)

**Comment by LCCarmody** [comment]
See consolidated ticket. Closing
