### ISSUE TITLE
NTR: uncooked cornstarch supplementation

### ISSUE THREAD

**Issue by laurenechan** [monarch-initiative/MAxO#96]
Parent: dietary intervention (MAXO:0000088) OR nutritional supplementation (MAXO:0000106)
Label: uncooked cornstarch supplementation
Exact synonym: administration of uncooked cornstarch, uncooked cornstarch therapy
Definition: Supplementation of uncooked cornstarch intended to prevent hepatomegaly and hypoglycemia, typically for individuals with irregular hepatic glycogen storage. Supplementation can include both regular cornstarch and extended release cornstarch. 
Reference: PMID:26303612, PMID:2403059

Use cases: glycogen storage diseases

**Comment by LCCarmody** [comment]
See issue https://github.com/monarch-initiative/MAxO/issues/18

**Comment by LCCarmody** [comment]
Please add.

**Comment by laurenechan** [comment]
@LCCarmody 
I'm going to add this under 'dietary intervention' as opposed to 'nutritional supplementation' as 'nutritional supplementation' seems to depict only things that are absent or deficient from the diet in a way we would describe something like a micronutrient inadequacy. You can't necessarily be "deficient" in cornstarch in the same way I don't think... 
Let me know if you would prefer a different parent class and we can adjust!
